// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: category/category_query.proto

package category

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategoryQueryService_FindMonthlyTotalPrices_FullMethodName           = "/pb.category.CategoryQueryService/FindMonthlyTotalPrices"
	CategoryQueryService_FindYearlyTotalPrices_FullMethodName            = "/pb.category.CategoryQueryService/FindYearlyTotalPrices"
	CategoryQueryService_FindMonthlyTotalPricesById_FullMethodName       = "/pb.category.CategoryQueryService/FindMonthlyTotalPricesById"
	CategoryQueryService_FindYearlyTotalPricesById_FullMethodName        = "/pb.category.CategoryQueryService/FindYearlyTotalPricesById"
	CategoryQueryService_FindMonthlyTotalPricesByMerchant_FullMethodName = "/pb.category.CategoryQueryService/FindMonthlyTotalPricesByMerchant"
	CategoryQueryService_FindYearlyTotalPricesByMerchant_FullMethodName  = "/pb.category.CategoryQueryService/FindYearlyTotalPricesByMerchant"
	CategoryQueryService_FindMonthPrice_FullMethodName                   = "/pb.category.CategoryQueryService/FindMonthPrice"
	CategoryQueryService_FindYearPrice_FullMethodName                    = "/pb.category.CategoryQueryService/FindYearPrice"
	CategoryQueryService_FindMonthPriceByMerchant_FullMethodName         = "/pb.category.CategoryQueryService/FindMonthPriceByMerchant"
	CategoryQueryService_FindYearPriceByMerchant_FullMethodName          = "/pb.category.CategoryQueryService/FindYearPriceByMerchant"
	CategoryQueryService_FindMonthPriceById_FullMethodName               = "/pb.category.CategoryQueryService/FindMonthPriceById"
	CategoryQueryService_FindYearPriceById_FullMethodName                = "/pb.category.CategoryQueryService/FindYearPriceById"
	CategoryQueryService_FindAll_FullMethodName                          = "/pb.category.CategoryQueryService/FindAll"
	CategoryQueryService_FindById_FullMethodName                         = "/pb.category.CategoryQueryService/FindById"
	CategoryQueryService_FindByActive_FullMethodName                     = "/pb.category.CategoryQueryService/FindByActive"
	CategoryQueryService_FindByTrashed_FullMethodName                    = "/pb.category.CategoryQueryService/FindByTrashed"
)

// CategoryQueryServiceClient is the client API for CategoryQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryQueryServiceClient interface {
	FindMonthlyTotalPrices(ctx context.Context, in *FindYearMonthTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPrices(ctx context.Context, in *FindYearTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthlyTotalPricesById(ctx context.Context, in *FindYearMonthTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesById(ctx context.Context, in *FindYearTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthlyTotalPricesByMerchant(ctx context.Context, in *FindYearMonthTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesByMerchant(ctx context.Context, in *FindYearTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error)
	FindYearPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error)
	FindMonthPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error)
	FindMonthPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error)
	FindAll(ctx context.Context, in *FindAllCategoryRequest, opts ...grpc.CallOption) (*ApiResponsePaginationCategory, error)
	FindById(ctx context.Context, in *FindByIdCategoryRequest, opts ...grpc.CallOption) (*ApiResponseCategory, error)
	FindByActive(ctx context.Context, in *FindAllCategoryRequest, opts ...grpc.CallOption) (*ApiResponsePaginationCategoryDeleteAt, error)
	FindByTrashed(ctx context.Context, in *FindAllCategoryRequest, opts ...grpc.CallOption) (*ApiResponsePaginationCategoryDeleteAt, error)
}

type categoryQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryQueryServiceClient(cc grpc.ClientConnInterface) CategoryQueryServiceClient {
	return &categoryQueryServiceClient{cc}
}

func (c *categoryQueryServiceClient) FindMonthlyTotalPrices(ctx context.Context, in *FindYearMonthTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindMonthlyTotalPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindYearlyTotalPrices(ctx context.Context, in *FindYearTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindYearlyTotalPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindMonthlyTotalPricesById(ctx context.Context, in *FindYearMonthTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindMonthlyTotalPricesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindYearlyTotalPricesById(ctx context.Context, in *FindYearTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindYearlyTotalPricesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindMonthlyTotalPricesByMerchant(ctx context.Context, in *FindYearMonthTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindMonthlyTotalPricesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindYearlyTotalPricesByMerchant(ctx context.Context, in *FindYearTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindYearlyTotalPricesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindMonthPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindMonthPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindYearPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindYearPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindMonthPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindMonthPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindYearPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindYearPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindMonthPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindMonthPriceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindYearPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindYearPriceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindAll(ctx context.Context, in *FindAllCategoryRequest, opts ...grpc.CallOption) (*ApiResponsePaginationCategory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationCategory)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindById(ctx context.Context, in *FindByIdCategoryRequest, opts ...grpc.CallOption) (*ApiResponseCategory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategory)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindByActive(ctx context.Context, in *FindAllCategoryRequest, opts ...grpc.CallOption) (*ApiResponsePaginationCategoryDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationCategoryDeleteAt)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindByActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryQueryServiceClient) FindByTrashed(ctx context.Context, in *FindAllCategoryRequest, opts ...grpc.CallOption) (*ApiResponsePaginationCategoryDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationCategoryDeleteAt)
	err := c.cc.Invoke(ctx, CategoryQueryService_FindByTrashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryQueryServiceServer is the server API for CategoryQueryService service.
// All implementations must embed UnimplementedCategoryQueryServiceServer
// for forward compatibility.
type CategoryQueryServiceServer interface {
	FindMonthlyTotalPrices(context.Context, *FindYearMonthTotalPrices) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPrices(context.Context, *FindYearTotalPrices) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthlyTotalPricesById(context.Context, *FindYearMonthTotalPriceById) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesById(context.Context, *FindYearTotalPriceById) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthlyTotalPricesByMerchant(context.Context, *FindYearMonthTotalPriceByMerchant) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesByMerchant(context.Context, *FindYearTotalPriceByMerchant) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryMonthPrice, error)
	FindYearPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryYearPrice, error)
	FindMonthPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryYearPrice, error)
	FindMonthPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryYearPrice, error)
	FindAll(context.Context, *FindAllCategoryRequest) (*ApiResponsePaginationCategory, error)
	FindById(context.Context, *FindByIdCategoryRequest) (*ApiResponseCategory, error)
	FindByActive(context.Context, *FindAllCategoryRequest) (*ApiResponsePaginationCategoryDeleteAt, error)
	FindByTrashed(context.Context, *FindAllCategoryRequest) (*ApiResponsePaginationCategoryDeleteAt, error)
	mustEmbedUnimplementedCategoryQueryServiceServer()
}

// UnimplementedCategoryQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryQueryServiceServer struct{}

func (UnimplementedCategoryQueryServiceServer) FindMonthlyTotalPrices(context.Context, *FindYearMonthTotalPrices) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalPrices not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindYearlyTotalPrices(context.Context, *FindYearTotalPrices) (*ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalPrices not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindMonthlyTotalPricesById(context.Context, *FindYearMonthTotalPriceById) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalPricesById not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindYearlyTotalPricesById(context.Context, *FindYearTotalPriceById) (*ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalPricesById not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindMonthlyTotalPricesByMerchant(context.Context, *FindYearMonthTotalPriceByMerchant) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthlyTotalPricesByMerchant not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindYearlyTotalPricesByMerchant(context.Context, *FindYearTotalPriceByMerchant) (*ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearlyTotalPricesByMerchant not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindMonthPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryMonthPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthPrice not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindYearPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryYearPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearPrice not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindMonthPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryMonthPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthPriceByMerchant not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindYearPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryYearPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearPriceByMerchant not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindMonthPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryMonthPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMonthPriceById not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindYearPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryYearPrice, error) {
	return nil, status.Error(codes.Unimplemented, "method FindYearPriceById not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindAll(context.Context, *FindAllCategoryRequest) (*ApiResponsePaginationCategory, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindById(context.Context, *FindByIdCategoryRequest) (*ApiResponseCategory, error) {
	return nil, status.Error(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindByActive(context.Context, *FindAllCategoryRequest) (*ApiResponsePaginationCategoryDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByActive not implemented")
}
func (UnimplementedCategoryQueryServiceServer) FindByTrashed(context.Context, *FindAllCategoryRequest) (*ApiResponsePaginationCategoryDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByTrashed not implemented")
}
func (UnimplementedCategoryQueryServiceServer) mustEmbedUnimplementedCategoryQueryServiceServer() {}
func (UnimplementedCategoryQueryServiceServer) testEmbeddedByValue()                              {}

// UnsafeCategoryQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryQueryServiceServer will
// result in compilation errors.
type UnsafeCategoryQueryServiceServer interface {
	mustEmbedUnimplementedCategoryQueryServiceServer()
}

func RegisterCategoryQueryServiceServer(s grpc.ServiceRegistrar, srv CategoryQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedCategoryQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryQueryService_ServiceDesc, srv)
}

func _CategoryQueryService_FindMonthlyTotalPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindMonthlyTotalPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindMonthlyTotalPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindMonthlyTotalPrices(ctx, req.(*FindYearMonthTotalPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindYearlyTotalPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindYearlyTotalPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindYearlyTotalPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindYearlyTotalPrices(ctx, req.(*FindYearTotalPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindMonthlyTotalPricesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalPriceById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindMonthlyTotalPricesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindMonthlyTotalPricesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindMonthlyTotalPricesById(ctx, req.(*FindYearMonthTotalPriceById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindYearlyTotalPricesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalPriceById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindYearlyTotalPricesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindYearlyTotalPricesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindYearlyTotalPricesById(ctx, req.(*FindYearTotalPriceById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindMonthlyTotalPricesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalPriceByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindMonthlyTotalPricesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindMonthlyTotalPricesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindMonthlyTotalPricesByMerchant(ctx, req.(*FindYearMonthTotalPriceByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindYearlyTotalPricesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalPriceByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindYearlyTotalPricesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindYearlyTotalPricesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindYearlyTotalPricesByMerchant(ctx, req.(*FindYearTotalPriceByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindMonthPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindMonthPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindMonthPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindMonthPrice(ctx, req.(*FindYearCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindYearPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindYearPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindYearPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindYearPrice(ctx, req.(*FindYearCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindMonthPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindMonthPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindMonthPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindMonthPriceByMerchant(ctx, req.(*FindYearCategoryByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindYearPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindYearPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindYearPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindYearPriceByMerchant(ctx, req.(*FindYearCategoryByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindMonthPriceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindMonthPriceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindMonthPriceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindMonthPriceById(ctx, req.(*FindYearCategoryById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindYearPriceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindYearPriceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindYearPriceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindYearPriceById(ctx, req.(*FindYearCategoryById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindAll(ctx, req.(*FindAllCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindById(ctx, req.(*FindByIdCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindByActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindByActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindByActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindByActive(ctx, req.(*FindAllCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryQueryService_FindByTrashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryQueryServiceServer).FindByTrashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryQueryService_FindByTrashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryQueryServiceServer).FindByTrashed(ctx, req.(*FindAllCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryQueryService_ServiceDesc is the grpc.ServiceDesc for CategoryQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.category.CategoryQueryService",
	HandlerType: (*CategoryQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalPrices",
			Handler:    _CategoryQueryService_FindMonthlyTotalPrices_Handler,
		},
		{
			MethodName: "FindYearlyTotalPrices",
			Handler:    _CategoryQueryService_FindYearlyTotalPrices_Handler,
		},
		{
			MethodName: "FindMonthlyTotalPricesById",
			Handler:    _CategoryQueryService_FindMonthlyTotalPricesById_Handler,
		},
		{
			MethodName: "FindYearlyTotalPricesById",
			Handler:    _CategoryQueryService_FindYearlyTotalPricesById_Handler,
		},
		{
			MethodName: "FindMonthlyTotalPricesByMerchant",
			Handler:    _CategoryQueryService_FindMonthlyTotalPricesByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyTotalPricesByMerchant",
			Handler:    _CategoryQueryService_FindYearlyTotalPricesByMerchant_Handler,
		},
		{
			MethodName: "FindMonthPrice",
			Handler:    _CategoryQueryService_FindMonthPrice_Handler,
		},
		{
			MethodName: "FindYearPrice",
			Handler:    _CategoryQueryService_FindYearPrice_Handler,
		},
		{
			MethodName: "FindMonthPriceByMerchant",
			Handler:    _CategoryQueryService_FindMonthPriceByMerchant_Handler,
		},
		{
			MethodName: "FindYearPriceByMerchant",
			Handler:    _CategoryQueryService_FindYearPriceByMerchant_Handler,
		},
		{
			MethodName: "FindMonthPriceById",
			Handler:    _CategoryQueryService_FindMonthPriceById_Handler,
		},
		{
			MethodName: "FindYearPriceById",
			Handler:    _CategoryQueryService_FindYearPriceById_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _CategoryQueryService_FindAll_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _CategoryQueryService_FindById_Handler,
		},
		{
			MethodName: "FindByActive",
			Handler:    _CategoryQueryService_FindByActive_Handler,
		},
		{
			MethodName: "FindByTrashed",
			Handler:    _CategoryQueryService_FindByTrashed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "category/category_query.proto",
}
