// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: category/category_stats.proto

package category

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_category_category_stats_proto protoreflect.FileDescriptor

const file_category_category_stats_proto_rawDesc = "" +
	"\n" +
	"\x1dcategory/category_stats.proto\x12\vpb.category\x1a\x1ecategory/category_common.proto2\xaf\x03\n" +
	"\x14CategoryStatsService\x12r\n" +
	"\x16FindMonthlyTotalPrices\x12%.pb.category.FindYearMonthTotalPrices\x1a1.pb.category.ApiResponseCategoryMonthlyTotalPrice\x12k\n" +
	"\x15FindYearlyTotalPrices\x12 .pb.category.FindYearTotalPrices\x1a0.pb.category.ApiResponseCategoryYearlyTotalPrice\x12[\n" +
	"\x0eFindMonthPrice\x12\x1d.pb.category.FindYearCategory\x1a*.pb.category.ApiResponseCategoryMonthPrice\x12Y\n" +
	"\rFindYearPrice\x12\x1d.pb.category.FindYearCategory\x1a).pb.category.ApiResponseCategoryYearPriceB>Z<github.com/MamangRust/monolith-graphql-ecommerce-pb/categoryb\x06proto3"

var file_category_category_stats_proto_goTypes = []any{
	(*FindYearMonthTotalPrices)(nil),             // 0: pb.category.FindYearMonthTotalPrices
	(*FindYearTotalPrices)(nil),                  // 1: pb.category.FindYearTotalPrices
	(*FindYearCategory)(nil),                     // 2: pb.category.FindYearCategory
	(*ApiResponseCategoryMonthlyTotalPrice)(nil), // 3: pb.category.ApiResponseCategoryMonthlyTotalPrice
	(*ApiResponseCategoryYearlyTotalPrice)(nil),  // 4: pb.category.ApiResponseCategoryYearlyTotalPrice
	(*ApiResponseCategoryMonthPrice)(nil),        // 5: pb.category.ApiResponseCategoryMonthPrice
	(*ApiResponseCategoryYearPrice)(nil),         // 6: pb.category.ApiResponseCategoryYearPrice
}
var file_category_category_stats_proto_depIdxs = []int32{
	0, // 0: pb.category.CategoryStatsService.FindMonthlyTotalPrices:input_type -> pb.category.FindYearMonthTotalPrices
	1, // 1: pb.category.CategoryStatsService.FindYearlyTotalPrices:input_type -> pb.category.FindYearTotalPrices
	2, // 2: pb.category.CategoryStatsService.FindMonthPrice:input_type -> pb.category.FindYearCategory
	2, // 3: pb.category.CategoryStatsService.FindYearPrice:input_type -> pb.category.FindYearCategory
	3, // 4: pb.category.CategoryStatsService.FindMonthlyTotalPrices:output_type -> pb.category.ApiResponseCategoryMonthlyTotalPrice
	4, // 5: pb.category.CategoryStatsService.FindYearlyTotalPrices:output_type -> pb.category.ApiResponseCategoryYearlyTotalPrice
	5, // 6: pb.category.CategoryStatsService.FindMonthPrice:output_type -> pb.category.ApiResponseCategoryMonthPrice
	6, // 7: pb.category.CategoryStatsService.FindYearPrice:output_type -> pb.category.ApiResponseCategoryYearPrice
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_category_category_stats_proto_init() }
func file_category_category_stats_proto_init() {
	if File_category_category_stats_proto != nil {
		return
	}
	file_category_category_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_category_stats_proto_rawDesc), len(file_category_category_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_category_stats_proto_goTypes,
		DependencyIndexes: file_category_category_stats_proto_depIdxs,
	}.Build()
	File_category_category_stats_proto = out.File
	file_category_category_stats_proto_goTypes = nil
	file_category_category_stats_proto_depIdxs = nil
}
