// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: category/category_query.proto

package category

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllCategoryRequest) Reset() {
	*x = FindAllCategoryRequest{}
	mi := &file_category_category_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllCategoryRequest) ProtoMessage() {}

func (x *FindAllCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_category_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllCategoryRequest.ProtoReflect.Descriptor instead.
func (*FindAllCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_category_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllCategoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllCategoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllCategoryRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

var File_category_category_query_proto protoreflect.FileDescriptor

const file_category_category_query_proto_rawDesc = "" +
	"\n" +
	"\x1dcategory/category_query.proto\x12\vpb.category\x1a\x1ecategory/category_common.proto\"a\n" +
	"\x16FindAllCategoryRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search2\xd1\r\n" +
	"\x14CategoryQueryService\x12r\n" +
	"\x16FindMonthlyTotalPrices\x12%.pb.category.FindYearMonthTotalPrices\x1a1.pb.category.ApiResponseCategoryMonthlyTotalPrice\x12k\n" +
	"\x15FindYearlyTotalPrices\x12 .pb.category.FindYearTotalPrices\x1a0.pb.category.ApiResponseCategoryYearlyTotalPrice\x12y\n" +
	"\x1aFindMonthlyTotalPricesById\x12(.pb.category.FindYearMonthTotalPriceById\x1a1.pb.category.ApiResponseCategoryMonthlyTotalPrice\x12r\n" +
	"\x19FindYearlyTotalPricesById\x12#.pb.category.FindYearTotalPriceById\x1a0.pb.category.ApiResponseCategoryYearlyTotalPrice\x12\x85\x01\n" +
	" FindMonthlyTotalPricesByMerchant\x12..pb.category.FindYearMonthTotalPriceByMerchant\x1a1.pb.category.ApiResponseCategoryMonthlyTotalPrice\x12~\n" +
	"\x1fFindYearlyTotalPricesByMerchant\x12).pb.category.FindYearTotalPriceByMerchant\x1a0.pb.category.ApiResponseCategoryYearlyTotalPrice\x12[\n" +
	"\x0eFindMonthPrice\x12\x1d.pb.category.FindYearCategory\x1a*.pb.category.ApiResponseCategoryMonthPrice\x12Y\n" +
	"\rFindYearPrice\x12\x1d.pb.category.FindYearCategory\x1a).pb.category.ApiResponseCategoryYearPrice\x12o\n" +
	"\x18FindMonthPriceByMerchant\x12'.pb.category.FindYearCategoryByMerchant\x1a*.pb.category.ApiResponseCategoryMonthPrice\x12m\n" +
	"\x17FindYearPriceByMerchant\x12'.pb.category.FindYearCategoryByMerchant\x1a).pb.category.ApiResponseCategoryYearPrice\x12c\n" +
	"\x12FindMonthPriceById\x12!.pb.category.FindYearCategoryById\x1a*.pb.category.ApiResponseCategoryMonthPrice\x12a\n" +
	"\x11FindYearPriceById\x12!.pb.category.FindYearCategoryById\x1a).pb.category.ApiResponseCategoryYearPrice\x12Z\n" +
	"\aFindAll\x12#.pb.category.FindAllCategoryRequest\x1a*.pb.category.ApiResponsePaginationCategory\x12R\n" +
	"\bFindById\x12$.pb.category.FindByIdCategoryRequest\x1a .pb.category.ApiResponseCategory\x12g\n" +
	"\fFindByActive\x12#.pb.category.FindAllCategoryRequest\x1a2.pb.category.ApiResponsePaginationCategoryDeleteAt\x12h\n" +
	"\rFindByTrashed\x12#.pb.category.FindAllCategoryRequest\x1a2.pb.category.ApiResponsePaginationCategoryDeleteAtB>Z<github.com/MamangRust/monolith-graphql-ecommerce-pb/categoryb\x06proto3"

var (
	file_category_category_query_proto_rawDescOnce sync.Once
	file_category_category_query_proto_rawDescData []byte
)

func file_category_category_query_proto_rawDescGZIP() []byte {
	file_category_category_query_proto_rawDescOnce.Do(func() {
		file_category_category_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_category_query_proto_rawDesc), len(file_category_category_query_proto_rawDesc)))
	})
	return file_category_category_query_proto_rawDescData
}

var file_category_category_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_category_category_query_proto_goTypes = []any{
	(*FindAllCategoryRequest)(nil),                // 0: pb.category.FindAllCategoryRequest
	(*FindYearMonthTotalPrices)(nil),              // 1: pb.category.FindYearMonthTotalPrices
	(*FindYearTotalPrices)(nil),                   // 2: pb.category.FindYearTotalPrices
	(*FindYearMonthTotalPriceById)(nil),           // 3: pb.category.FindYearMonthTotalPriceById
	(*FindYearTotalPriceById)(nil),                // 4: pb.category.FindYearTotalPriceById
	(*FindYearMonthTotalPriceByMerchant)(nil),     // 5: pb.category.FindYearMonthTotalPriceByMerchant
	(*FindYearTotalPriceByMerchant)(nil),          // 6: pb.category.FindYearTotalPriceByMerchant
	(*FindYearCategory)(nil),                      // 7: pb.category.FindYearCategory
	(*FindYearCategoryByMerchant)(nil),            // 8: pb.category.FindYearCategoryByMerchant
	(*FindYearCategoryById)(nil),                  // 9: pb.category.FindYearCategoryById
	(*FindByIdCategoryRequest)(nil),               // 10: pb.category.FindByIdCategoryRequest
	(*ApiResponseCategoryMonthlyTotalPrice)(nil),  // 11: pb.category.ApiResponseCategoryMonthlyTotalPrice
	(*ApiResponseCategoryYearlyTotalPrice)(nil),   // 12: pb.category.ApiResponseCategoryYearlyTotalPrice
	(*ApiResponseCategoryMonthPrice)(nil),         // 13: pb.category.ApiResponseCategoryMonthPrice
	(*ApiResponseCategoryYearPrice)(nil),          // 14: pb.category.ApiResponseCategoryYearPrice
	(*ApiResponsePaginationCategory)(nil),         // 15: pb.category.ApiResponsePaginationCategory
	(*ApiResponseCategory)(nil),                   // 16: pb.category.ApiResponseCategory
	(*ApiResponsePaginationCategoryDeleteAt)(nil), // 17: pb.category.ApiResponsePaginationCategoryDeleteAt
}
var file_category_category_query_proto_depIdxs = []int32{
	1,  // 0: pb.category.CategoryQueryService.FindMonthlyTotalPrices:input_type -> pb.category.FindYearMonthTotalPrices
	2,  // 1: pb.category.CategoryQueryService.FindYearlyTotalPrices:input_type -> pb.category.FindYearTotalPrices
	3,  // 2: pb.category.CategoryQueryService.FindMonthlyTotalPricesById:input_type -> pb.category.FindYearMonthTotalPriceById
	4,  // 3: pb.category.CategoryQueryService.FindYearlyTotalPricesById:input_type -> pb.category.FindYearTotalPriceById
	5,  // 4: pb.category.CategoryQueryService.FindMonthlyTotalPricesByMerchant:input_type -> pb.category.FindYearMonthTotalPriceByMerchant
	6,  // 5: pb.category.CategoryQueryService.FindYearlyTotalPricesByMerchant:input_type -> pb.category.FindYearTotalPriceByMerchant
	7,  // 6: pb.category.CategoryQueryService.FindMonthPrice:input_type -> pb.category.FindYearCategory
	7,  // 7: pb.category.CategoryQueryService.FindYearPrice:input_type -> pb.category.FindYearCategory
	8,  // 8: pb.category.CategoryQueryService.FindMonthPriceByMerchant:input_type -> pb.category.FindYearCategoryByMerchant
	8,  // 9: pb.category.CategoryQueryService.FindYearPriceByMerchant:input_type -> pb.category.FindYearCategoryByMerchant
	9,  // 10: pb.category.CategoryQueryService.FindMonthPriceById:input_type -> pb.category.FindYearCategoryById
	9,  // 11: pb.category.CategoryQueryService.FindYearPriceById:input_type -> pb.category.FindYearCategoryById
	0,  // 12: pb.category.CategoryQueryService.FindAll:input_type -> pb.category.FindAllCategoryRequest
	10, // 13: pb.category.CategoryQueryService.FindById:input_type -> pb.category.FindByIdCategoryRequest
	0,  // 14: pb.category.CategoryQueryService.FindByActive:input_type -> pb.category.FindAllCategoryRequest
	0,  // 15: pb.category.CategoryQueryService.FindByTrashed:input_type -> pb.category.FindAllCategoryRequest
	11, // 16: pb.category.CategoryQueryService.FindMonthlyTotalPrices:output_type -> pb.category.ApiResponseCategoryMonthlyTotalPrice
	12, // 17: pb.category.CategoryQueryService.FindYearlyTotalPrices:output_type -> pb.category.ApiResponseCategoryYearlyTotalPrice
	11, // 18: pb.category.CategoryQueryService.FindMonthlyTotalPricesById:output_type -> pb.category.ApiResponseCategoryMonthlyTotalPrice
	12, // 19: pb.category.CategoryQueryService.FindYearlyTotalPricesById:output_type -> pb.category.ApiResponseCategoryYearlyTotalPrice
	11, // 20: pb.category.CategoryQueryService.FindMonthlyTotalPricesByMerchant:output_type -> pb.category.ApiResponseCategoryMonthlyTotalPrice
	12, // 21: pb.category.CategoryQueryService.FindYearlyTotalPricesByMerchant:output_type -> pb.category.ApiResponseCategoryYearlyTotalPrice
	13, // 22: pb.category.CategoryQueryService.FindMonthPrice:output_type -> pb.category.ApiResponseCategoryMonthPrice
	14, // 23: pb.category.CategoryQueryService.FindYearPrice:output_type -> pb.category.ApiResponseCategoryYearPrice
	13, // 24: pb.category.CategoryQueryService.FindMonthPriceByMerchant:output_type -> pb.category.ApiResponseCategoryMonthPrice
	14, // 25: pb.category.CategoryQueryService.FindYearPriceByMerchant:output_type -> pb.category.ApiResponseCategoryYearPrice
	13, // 26: pb.category.CategoryQueryService.FindMonthPriceById:output_type -> pb.category.ApiResponseCategoryMonthPrice
	14, // 27: pb.category.CategoryQueryService.FindYearPriceById:output_type -> pb.category.ApiResponseCategoryYearPrice
	15, // 28: pb.category.CategoryQueryService.FindAll:output_type -> pb.category.ApiResponsePaginationCategory
	16, // 29: pb.category.CategoryQueryService.FindById:output_type -> pb.category.ApiResponseCategory
	17, // 30: pb.category.CategoryQueryService.FindByActive:output_type -> pb.category.ApiResponsePaginationCategoryDeleteAt
	17, // 31: pb.category.CategoryQueryService.FindByTrashed:output_type -> pb.category.ApiResponsePaginationCategoryDeleteAt
	16, // [16:32] is the sub-list for method output_type
	0,  // [0:16] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_category_category_query_proto_init() }
func file_category_category_query_proto_init() {
	if File_category_category_query_proto != nil {
		return
	}
	file_category_category_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_category_query_proto_rawDesc), len(file_category_category_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_category_query_proto_goTypes,
		DependencyIndexes: file_category_category_query_proto_depIdxs,
		MessageInfos:      file_category_category_query_proto_msgTypes,
	}.Build()
	File_category_category_query_proto = out.File
	file_category_category_query_proto_goTypes = nil
	file_category_category_query_proto_depIdxs = nil
}
