// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: category/category_stats_byid.proto

package category

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_category_category_stats_byid_proto protoreflect.FileDescriptor

const file_category_category_stats_byid_proto_rawDesc = "" +
	"\n" +
	"\"category/category_stats_byid.proto\x12\vpb.category\x1a\x1ecategory/category_common.proto2\xd1\x03\n" +
	"\x18CategoryStatsByIdService\x12y\n" +
	"\x1aFindMonthlyTotalPricesById\x12(.pb.category.FindYearMonthTotalPriceById\x1a1.pb.category.ApiResponseCategoryMonthlyTotalPrice\x12r\n" +
	"\x19FindYearlyTotalPricesById\x12#.pb.category.FindYearTotalPriceById\x1a0.pb.category.ApiResponseCategoryYearlyTotalPrice\x12c\n" +
	"\x12FindMonthPriceById\x12!.pb.category.FindYearCategoryById\x1a*.pb.category.ApiResponseCategoryMonthPrice\x12a\n" +
	"\x11FindYearPriceById\x12!.pb.category.FindYearCategoryById\x1a).pb.category.ApiResponseCategoryYearPriceB>Z<github.com/MamangRust/monolith-graphql-ecommerce-pb/categoryb\x06proto3"

var file_category_category_stats_byid_proto_goTypes = []any{
	(*FindYearMonthTotalPriceById)(nil),          // 0: pb.category.FindYearMonthTotalPriceById
	(*FindYearTotalPriceById)(nil),               // 1: pb.category.FindYearTotalPriceById
	(*FindYearCategoryById)(nil),                 // 2: pb.category.FindYearCategoryById
	(*ApiResponseCategoryMonthlyTotalPrice)(nil), // 3: pb.category.ApiResponseCategoryMonthlyTotalPrice
	(*ApiResponseCategoryYearlyTotalPrice)(nil),  // 4: pb.category.ApiResponseCategoryYearlyTotalPrice
	(*ApiResponseCategoryMonthPrice)(nil),        // 5: pb.category.ApiResponseCategoryMonthPrice
	(*ApiResponseCategoryYearPrice)(nil),         // 6: pb.category.ApiResponseCategoryYearPrice
}
var file_category_category_stats_byid_proto_depIdxs = []int32{
	0, // 0: pb.category.CategoryStatsByIdService.FindMonthlyTotalPricesById:input_type -> pb.category.FindYearMonthTotalPriceById
	1, // 1: pb.category.CategoryStatsByIdService.FindYearlyTotalPricesById:input_type -> pb.category.FindYearTotalPriceById
	2, // 2: pb.category.CategoryStatsByIdService.FindMonthPriceById:input_type -> pb.category.FindYearCategoryById
	2, // 3: pb.category.CategoryStatsByIdService.FindYearPriceById:input_type -> pb.category.FindYearCategoryById
	3, // 4: pb.category.CategoryStatsByIdService.FindMonthlyTotalPricesById:output_type -> pb.category.ApiResponseCategoryMonthlyTotalPrice
	4, // 5: pb.category.CategoryStatsByIdService.FindYearlyTotalPricesById:output_type -> pb.category.ApiResponseCategoryYearlyTotalPrice
	5, // 6: pb.category.CategoryStatsByIdService.FindMonthPriceById:output_type -> pb.category.ApiResponseCategoryMonthPrice
	6, // 7: pb.category.CategoryStatsByIdService.FindYearPriceById:output_type -> pb.category.ApiResponseCategoryYearPrice
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_category_category_stats_byid_proto_init() }
func file_category_category_stats_byid_proto_init() {
	if File_category_category_stats_byid_proto != nil {
		return
	}
	file_category_category_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_category_stats_byid_proto_rawDesc), len(file_category_category_stats_byid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_category_stats_byid_proto_goTypes,
		DependencyIndexes: file_category_category_stats_byid_proto_depIdxs,
	}.Build()
	File_category_category_stats_byid_proto = out.File
	file_category_category_stats_byid_proto_goTypes = nil
	file_category_category_stats_byid_proto_depIdxs = nil
}
