syntax = "proto3";

package pb;

option go_package = "github.com/MamangRust/monolith-graphql-ecommerce-pb";


import "category/category_common.proto";


service CategoryStatsService {
    rpc FindMonthlyTotalPrices(FindYearMonthTotalPrices) returns (ApiResponseCategoryMonthlyTotalPrice);
    rpc FindYearlyTotalPrices(FindYearTotalPrices) returns (ApiResponseCategoryYearlyTotalPrice);
    rpc FindMonthPrice(FindYearCategory) returns(ApiResponseCategoryMonthPrice);
    rpc FindYearPrice(FindYearCategory) returns(ApiResponseCategoryYearPrice);
}