// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: transaction/stats/transaction_stats.proto

package transaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionStatsService_GetMonthlyAmountSuccess_FullMethodName            = "/pb.transaction.stats.TransactionStatsService/GetMonthlyAmountSuccess"
	TransactionStatsService_GetYearlyAmountSuccess_FullMethodName             = "/pb.transaction.stats.TransactionStatsService/GetYearlyAmountSuccess"
	TransactionStatsService_GetMonthlyAmountFailed_FullMethodName             = "/pb.transaction.stats.TransactionStatsService/GetMonthlyAmountFailed"
	TransactionStatsService_GetYearlyAmountFailed_FullMethodName              = "/pb.transaction.stats.TransactionStatsService/GetYearlyAmountFailed"
	TransactionStatsService_GetMonthlyTransactionMethodSuccess_FullMethodName = "/pb.transaction.stats.TransactionStatsService/GetMonthlyTransactionMethodSuccess"
	TransactionStatsService_GetYearlyTransactionMethodSuccess_FullMethodName  = "/pb.transaction.stats.TransactionStatsService/GetYearlyTransactionMethodSuccess"
	TransactionStatsService_GetMonthlyTransactionMethodFailed_FullMethodName  = "/pb.transaction.stats.TransactionStatsService/GetMonthlyTransactionMethodFailed"
	TransactionStatsService_GetYearlyTransactionMethodFailed_FullMethodName   = "/pb.transaction.stats.TransactionStatsService/GetYearlyTransactionMethodFailed"
)

// TransactionStatsServiceClient is the client API for TransactionStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionStatsServiceClient interface {
	GetMonthlyAmountSuccess(ctx context.Context, in *MonthAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountSuccess, error)
	GetYearlyAmountSuccess(ctx context.Context, in *YearAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountSuccess, error)
	GetMonthlyAmountFailed(ctx context.Context, in *MonthAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountFailed, error)
	GetYearlyAmountFailed(ctx context.Context, in *YearAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountFailed, error)
	GetMonthlyTransactionMethodSuccess(ctx context.Context, in *MonthMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodSuccess(ctx context.Context, in *YearMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error)
	GetMonthlyTransactionMethodFailed(ctx context.Context, in *MonthMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodFailed(ctx context.Context, in *YearMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error)
}

type transactionStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionStatsServiceClient(cc grpc.ClientConnInterface) TransactionStatsServiceClient {
	return &transactionStatsServiceClient{cc}
}

func (c *transactionStatsServiceClient) GetMonthlyAmountSuccess(ctx context.Context, in *MonthAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetMonthlyAmountSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetYearlyAmountSuccess(ctx context.Context, in *YearAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetYearlyAmountSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetMonthlyAmountFailed(ctx context.Context, in *MonthAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthAmountFailed)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetMonthlyAmountFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetYearlyAmountFailed(ctx context.Context, in *YearAmountTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearAmountFailed)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetYearlyAmountFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetMonthlyTransactionMethodSuccess(ctx context.Context, in *MonthMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetMonthlyTransactionMethodSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetYearlyTransactionMethodSuccess(ctx context.Context, in *YearMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetYearlyTransactionMethodSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetMonthlyTransactionMethodFailed(ctx context.Context, in *MonthMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetMonthlyTransactionMethodFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionStatsServiceClient) GetYearlyTransactionMethodFailed(ctx context.Context, in *YearMethodTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionStatsService_GetYearlyTransactionMethodFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionStatsServiceServer is the server API for TransactionStatsService service.
// All implementations must embed UnimplementedTransactionStatsServiceServer
// for forward compatibility.
type TransactionStatsServiceServer interface {
	GetMonthlyAmountSuccess(context.Context, *MonthAmountTransactionRequest) (*ApiResponseTransactionMonthAmountSuccess, error)
	GetYearlyAmountSuccess(context.Context, *YearAmountTransactionRequest) (*ApiResponseTransactionYearAmountSuccess, error)
	GetMonthlyAmountFailed(context.Context, *MonthAmountTransactionRequest) (*ApiResponseTransactionMonthAmountFailed, error)
	GetYearlyAmountFailed(context.Context, *YearAmountTransactionRequest) (*ApiResponseTransactionYearAmountFailed, error)
	GetMonthlyTransactionMethodSuccess(context.Context, *MonthMethodTransactionRequest) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodSuccess(context.Context, *YearMethodTransactionRequest) (*ApiResponseTransactionYearPaymentmethod, error)
	GetMonthlyTransactionMethodFailed(context.Context, *MonthMethodTransactionRequest) (*ApiResponseTransactionMonthPaymentMethod, error)
	GetYearlyTransactionMethodFailed(context.Context, *YearMethodTransactionRequest) (*ApiResponseTransactionYearPaymentmethod, error)
	mustEmbedUnimplementedTransactionStatsServiceServer()
}

// UnimplementedTransactionStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionStatsServiceServer struct{}

func (UnimplementedTransactionStatsServiceServer) GetMonthlyAmountSuccess(context.Context, *MonthAmountTransactionRequest) (*ApiResponseTransactionMonthAmountSuccess, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthlyAmountSuccess not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetYearlyAmountSuccess(context.Context, *YearAmountTransactionRequest) (*ApiResponseTransactionYearAmountSuccess, error) {
	return nil, status.Error(codes.Unimplemented, "method GetYearlyAmountSuccess not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetMonthlyAmountFailed(context.Context, *MonthAmountTransactionRequest) (*ApiResponseTransactionMonthAmountFailed, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthlyAmountFailed not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetYearlyAmountFailed(context.Context, *YearAmountTransactionRequest) (*ApiResponseTransactionYearAmountFailed, error) {
	return nil, status.Error(codes.Unimplemented, "method GetYearlyAmountFailed not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetMonthlyTransactionMethodSuccess(context.Context, *MonthMethodTransactionRequest) (*ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthlyTransactionMethodSuccess not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetYearlyTransactionMethodSuccess(context.Context, *YearMethodTransactionRequest) (*ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Error(codes.Unimplemented, "method GetYearlyTransactionMethodSuccess not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetMonthlyTransactionMethodFailed(context.Context, *MonthMethodTransactionRequest) (*ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthlyTransactionMethodFailed not implemented")
}
func (UnimplementedTransactionStatsServiceServer) GetYearlyTransactionMethodFailed(context.Context, *YearMethodTransactionRequest) (*ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Error(codes.Unimplemented, "method GetYearlyTransactionMethodFailed not implemented")
}
func (UnimplementedTransactionStatsServiceServer) mustEmbedUnimplementedTransactionStatsServiceServer() {
}
func (UnimplementedTransactionStatsServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionStatsServiceServer will
// result in compilation errors.
type UnsafeTransactionStatsServiceServer interface {
	mustEmbedUnimplementedTransactionStatsServiceServer()
}

func RegisterTransactionStatsServiceServer(s grpc.ServiceRegistrar, srv TransactionStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionStatsService_ServiceDesc, srv)
}

func _TransactionStatsService_GetMonthlyAmountSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthAmountTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetMonthlyAmountSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetMonthlyAmountSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetMonthlyAmountSuccess(ctx, req.(*MonthAmountTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetYearlyAmountSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearAmountTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetYearlyAmountSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetYearlyAmountSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetYearlyAmountSuccess(ctx, req.(*YearAmountTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetMonthlyAmountFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthAmountTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetMonthlyAmountFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetMonthlyAmountFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetMonthlyAmountFailed(ctx, req.(*MonthAmountTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetYearlyAmountFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearAmountTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetYearlyAmountFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetYearlyAmountFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetYearlyAmountFailed(ctx, req.(*YearAmountTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetMonthlyTransactionMethodSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthMethodTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetMonthlyTransactionMethodSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetMonthlyTransactionMethodSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetMonthlyTransactionMethodSuccess(ctx, req.(*MonthMethodTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetYearlyTransactionMethodSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearMethodTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetYearlyTransactionMethodSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetYearlyTransactionMethodSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetYearlyTransactionMethodSuccess(ctx, req.(*YearMethodTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetMonthlyTransactionMethodFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthMethodTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetMonthlyTransactionMethodFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetMonthlyTransactionMethodFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetMonthlyTransactionMethodFailed(ctx, req.(*MonthMethodTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionStatsService_GetYearlyTransactionMethodFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearMethodTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionStatsServiceServer).GetYearlyTransactionMethodFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionStatsService_GetYearlyTransactionMethodFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionStatsServiceServer).GetYearlyTransactionMethodFailed(ctx, req.(*YearMethodTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionStatsService_ServiceDesc is the grpc.ServiceDesc for TransactionStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.transaction.stats.TransactionStatsService",
	HandlerType: (*TransactionStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonthlyAmountSuccess",
			Handler:    _TransactionStatsService_GetMonthlyAmountSuccess_Handler,
		},
		{
			MethodName: "GetYearlyAmountSuccess",
			Handler:    _TransactionStatsService_GetYearlyAmountSuccess_Handler,
		},
		{
			MethodName: "GetMonthlyAmountFailed",
			Handler:    _TransactionStatsService_GetMonthlyAmountFailed_Handler,
		},
		{
			MethodName: "GetYearlyAmountFailed",
			Handler:    _TransactionStatsService_GetYearlyAmountFailed_Handler,
		},
		{
			MethodName: "GetMonthlyTransactionMethodSuccess",
			Handler:    _TransactionStatsService_GetMonthlyTransactionMethodSuccess_Handler,
		},
		{
			MethodName: "GetYearlyTransactionMethodSuccess",
			Handler:    _TransactionStatsService_GetYearlyTransactionMethodSuccess_Handler,
		},
		{
			MethodName: "GetMonthlyTransactionMethodFailed",
			Handler:    _TransactionStatsService_GetMonthlyTransactionMethodFailed_Handler,
		},
		{
			MethodName: "GetYearlyTransactionMethodFailed",
			Handler:    _TransactionStatsService_GetYearlyTransactionMethodFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/stats/transaction_stats.proto",
}
