// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transaction/stats/transaction_stats_bymerchant.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonthAmountTransactionMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthAmountTransactionMerchantRequest) Reset() {
	*x = MonthAmountTransactionMerchantRequest{}
	mi := &file_transaction_stats_transaction_stats_bymerchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthAmountTransactionMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthAmountTransactionMerchantRequest) ProtoMessage() {}

func (x *MonthAmountTransactionMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_stats_transaction_stats_bymerchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthAmountTransactionMerchantRequest.ProtoReflect.Descriptor instead.
func (*MonthAmountTransactionMerchantRequest) Descriptor() ([]byte, []int) {
	return file_transaction_stats_transaction_stats_bymerchant_proto_rawDescGZIP(), []int{0}
}

func (x *MonthAmountTransactionMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MonthAmountTransactionMerchantRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MonthAmountTransactionMerchantRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type YearAmountTransactionMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearAmountTransactionMerchantRequest) Reset() {
	*x = YearAmountTransactionMerchantRequest{}
	mi := &file_transaction_stats_transaction_stats_bymerchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearAmountTransactionMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearAmountTransactionMerchantRequest) ProtoMessage() {}

func (x *YearAmountTransactionMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_stats_transaction_stats_bymerchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearAmountTransactionMerchantRequest.ProtoReflect.Descriptor instead.
func (*YearAmountTransactionMerchantRequest) Descriptor() ([]byte, []int) {
	return file_transaction_stats_transaction_stats_bymerchant_proto_rawDescGZIP(), []int{1}
}

func (x *YearAmountTransactionMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *YearAmountTransactionMerchantRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type MonthMethodTransactionMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthMethodTransactionMerchantRequest) Reset() {
	*x = MonthMethodTransactionMerchantRequest{}
	mi := &file_transaction_stats_transaction_stats_bymerchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthMethodTransactionMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthMethodTransactionMerchantRequest) ProtoMessage() {}

func (x *MonthMethodTransactionMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_stats_transaction_stats_bymerchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthMethodTransactionMerchantRequest.ProtoReflect.Descriptor instead.
func (*MonthMethodTransactionMerchantRequest) Descriptor() ([]byte, []int) {
	return file_transaction_stats_transaction_stats_bymerchant_proto_rawDescGZIP(), []int{2}
}

func (x *MonthMethodTransactionMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MonthMethodTransactionMerchantRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MonthMethodTransactionMerchantRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type YearMethodTransactionMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearMethodTransactionMerchantRequest) Reset() {
	*x = YearMethodTransactionMerchantRequest{}
	mi := &file_transaction_stats_transaction_stats_bymerchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearMethodTransactionMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearMethodTransactionMerchantRequest) ProtoMessage() {}

func (x *YearMethodTransactionMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_stats_transaction_stats_bymerchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearMethodTransactionMerchantRequest.ProtoReflect.Descriptor instead.
func (*YearMethodTransactionMerchantRequest) Descriptor() ([]byte, []int) {
	return file_transaction_stats_transaction_stats_bymerchant_proto_rawDescGZIP(), []int{3}
}

func (x *YearMethodTransactionMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *YearMethodTransactionMerchantRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

var File_transaction_stats_transaction_stats_bymerchant_proto protoreflect.FileDescriptor

const file_transaction_stats_transaction_stats_bymerchant_proto_rawDesc = "" +
	"\n" +
	"4transaction/stats/transaction_stats_bymerchant.proto\x12\x14pb.transaction.stats\x1a$transaction/transaction_common.proto\"r\n" +
	"%MonthAmountTransactionMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"[\n" +
	"$YearAmountTransactionMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"r\n" +
	"%MonthMethodTransactionMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"[\n" +
	"$YearMethodTransactionMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year2\xa5\n" +
	"\n" +
	"!TransactionStatsByMerchantService\x12\x9a\x01\n" +
	"!GetMonthlyAmountSuccessByMerchant\x12;.pb.transaction.stats.MonthAmountTransactionMerchantRequest\x1a8.pb.transaction.ApiResponseTransactionMonthAmountSuccess\x12\x97\x01\n" +
	" GetYearlyAmountSuccessByMerchant\x12:.pb.transaction.stats.YearAmountTransactionMerchantRequest\x1a7.pb.transaction.ApiResponseTransactionYearAmountSuccess\x12\x98\x01\n" +
	" GetMonthlyAmountFailedByMerchant\x12;.pb.transaction.stats.MonthAmountTransactionMerchantRequest\x1a7.pb.transaction.ApiResponseTransactionMonthAmountFailed\x12\x95\x01\n" +
	"\x1fGetYearlyAmountFailedByMerchant\x12:.pb.transaction.stats.YearAmountTransactionMerchantRequest\x1a6.pb.transaction.ApiResponseTransactionYearAmountFailed\x12\xa5\x01\n" +
	",GetMonthlyTransactionMethodByMerchantSuccess\x12;.pb.transaction.stats.MonthMethodTransactionMerchantRequest\x1a8.pb.transaction.ApiResponseTransactionMonthPaymentMethod\x12\xa2\x01\n" +
	"+GetYearlyTransactionMethodByMerchantSuccess\x12:.pb.transaction.stats.YearMethodTransactionMerchantRequest\x1a7.pb.transaction.ApiResponseTransactionYearPaymentmethod\x12\xa4\x01\n" +
	"+GetMonthlyTransactionMethodByMerchantFailed\x12;.pb.transaction.stats.MonthMethodTransactionMerchantRequest\x1a8.pb.transaction.ApiResponseTransactionMonthPaymentMethod\x12\xa1\x01\n" +
	"*GetYearlyTransactionMethodByMerchantFailed\x12:.pb.transaction.stats.YearMethodTransactionMerchantRequest\x1a7.pb.transaction.ApiResponseTransactionYearPaymentmethodBAZ?github.com/MamangRust/monolith-graphql-ecommerce-pb/transactionb\x06proto3"

var (
	file_transaction_stats_transaction_stats_bymerchant_proto_rawDescOnce sync.Once
	file_transaction_stats_transaction_stats_bymerchant_proto_rawDescData []byte
)

func file_transaction_stats_transaction_stats_bymerchant_proto_rawDescGZIP() []byte {
	file_transaction_stats_transaction_stats_bymerchant_proto_rawDescOnce.Do(func() {
		file_transaction_stats_transaction_stats_bymerchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_stats_transaction_stats_bymerchant_proto_rawDesc), len(file_transaction_stats_transaction_stats_bymerchant_proto_rawDesc)))
	})
	return file_transaction_stats_transaction_stats_bymerchant_proto_rawDescData
}

var file_transaction_stats_transaction_stats_bymerchant_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transaction_stats_transaction_stats_bymerchant_proto_goTypes = []any{
	(*MonthAmountTransactionMerchantRequest)(nil),    // 0: pb.transaction.stats.MonthAmountTransactionMerchantRequest
	(*YearAmountTransactionMerchantRequest)(nil),     // 1: pb.transaction.stats.YearAmountTransactionMerchantRequest
	(*MonthMethodTransactionMerchantRequest)(nil),    // 2: pb.transaction.stats.MonthMethodTransactionMerchantRequest
	(*YearMethodTransactionMerchantRequest)(nil),     // 3: pb.transaction.stats.YearMethodTransactionMerchantRequest
	(*ApiResponseTransactionMonthAmountSuccess)(nil), // 4: pb.transaction.ApiResponseTransactionMonthAmountSuccess
	(*ApiResponseTransactionYearAmountSuccess)(nil),  // 5: pb.transaction.ApiResponseTransactionYearAmountSuccess
	(*ApiResponseTransactionMonthAmountFailed)(nil),  // 6: pb.transaction.ApiResponseTransactionMonthAmountFailed
	(*ApiResponseTransactionYearAmountFailed)(nil),   // 7: pb.transaction.ApiResponseTransactionYearAmountFailed
	(*ApiResponseTransactionMonthPaymentMethod)(nil), // 8: pb.transaction.ApiResponseTransactionMonthPaymentMethod
	(*ApiResponseTransactionYearPaymentmethod)(nil),  // 9: pb.transaction.ApiResponseTransactionYearPaymentmethod
}
var file_transaction_stats_transaction_stats_bymerchant_proto_depIdxs = []int32{
	0, // 0: pb.transaction.stats.TransactionStatsByMerchantService.GetMonthlyAmountSuccessByMerchant:input_type -> pb.transaction.stats.MonthAmountTransactionMerchantRequest
	1, // 1: pb.transaction.stats.TransactionStatsByMerchantService.GetYearlyAmountSuccessByMerchant:input_type -> pb.transaction.stats.YearAmountTransactionMerchantRequest
	0, // 2: pb.transaction.stats.TransactionStatsByMerchantService.GetMonthlyAmountFailedByMerchant:input_type -> pb.transaction.stats.MonthAmountTransactionMerchantRequest
	1, // 3: pb.transaction.stats.TransactionStatsByMerchantService.GetYearlyAmountFailedByMerchant:input_type -> pb.transaction.stats.YearAmountTransactionMerchantRequest
	2, // 4: pb.transaction.stats.TransactionStatsByMerchantService.GetMonthlyTransactionMethodByMerchantSuccess:input_type -> pb.transaction.stats.MonthMethodTransactionMerchantRequest
	3, // 5: pb.transaction.stats.TransactionStatsByMerchantService.GetYearlyTransactionMethodByMerchantSuccess:input_type -> pb.transaction.stats.YearMethodTransactionMerchantRequest
	2, // 6: pb.transaction.stats.TransactionStatsByMerchantService.GetMonthlyTransactionMethodByMerchantFailed:input_type -> pb.transaction.stats.MonthMethodTransactionMerchantRequest
	3, // 7: pb.transaction.stats.TransactionStatsByMerchantService.GetYearlyTransactionMethodByMerchantFailed:input_type -> pb.transaction.stats.YearMethodTransactionMerchantRequest
	4, // 8: pb.transaction.stats.TransactionStatsByMerchantService.GetMonthlyAmountSuccessByMerchant:output_type -> pb.transaction.ApiResponseTransactionMonthAmountSuccess
	5, // 9: pb.transaction.stats.TransactionStatsByMerchantService.GetYearlyAmountSuccessByMerchant:output_type -> pb.transaction.ApiResponseTransactionYearAmountSuccess
	6, // 10: pb.transaction.stats.TransactionStatsByMerchantService.GetMonthlyAmountFailedByMerchant:output_type -> pb.transaction.ApiResponseTransactionMonthAmountFailed
	7, // 11: pb.transaction.stats.TransactionStatsByMerchantService.GetYearlyAmountFailedByMerchant:output_type -> pb.transaction.ApiResponseTransactionYearAmountFailed
	8, // 12: pb.transaction.stats.TransactionStatsByMerchantService.GetMonthlyTransactionMethodByMerchantSuccess:output_type -> pb.transaction.ApiResponseTransactionMonthPaymentMethod
	9, // 13: pb.transaction.stats.TransactionStatsByMerchantService.GetYearlyTransactionMethodByMerchantSuccess:output_type -> pb.transaction.ApiResponseTransactionYearPaymentmethod
	8, // 14: pb.transaction.stats.TransactionStatsByMerchantService.GetMonthlyTransactionMethodByMerchantFailed:output_type -> pb.transaction.ApiResponseTransactionMonthPaymentMethod
	9, // 15: pb.transaction.stats.TransactionStatsByMerchantService.GetYearlyTransactionMethodByMerchantFailed:output_type -> pb.transaction.ApiResponseTransactionYearPaymentmethod
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_stats_transaction_stats_bymerchant_proto_init() }
func file_transaction_stats_transaction_stats_bymerchant_proto_init() {
	if File_transaction_stats_transaction_stats_bymerchant_proto != nil {
		return
	}
	file_transaction_transaction_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_stats_transaction_stats_bymerchant_proto_rawDesc), len(file_transaction_stats_transaction_stats_bymerchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_stats_transaction_stats_bymerchant_proto_goTypes,
		DependencyIndexes: file_transaction_stats_transaction_stats_bymerchant_proto_depIdxs,
		MessageInfos:      file_transaction_stats_transaction_stats_bymerchant_proto_msgTypes,
	}.Build()
	File_transaction_stats_transaction_stats_bymerchant_proto = out.File
	file_transaction_stats_transaction_stats_bymerchant_proto_goTypes = nil
	file_transaction_stats_transaction_stats_bymerchant_proto_depIdxs = nil
}
