// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: shipping_address/shipping_address_query.proto

package shipping_address

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShippingQueryService_FindAll_FullMethodName       = "/pb.shipping_address.ShippingQueryService/FindAll"
	ShippingQueryService_FindById_FullMethodName      = "/pb.shipping_address.ShippingQueryService/FindById"
	ShippingQueryService_FindByOrder_FullMethodName   = "/pb.shipping_address.ShippingQueryService/FindByOrder"
	ShippingQueryService_FindByActive_FullMethodName  = "/pb.shipping_address.ShippingQueryService/FindByActive"
	ShippingQueryService_FindByTrashed_FullMethodName = "/pb.shipping_address.ShippingQueryService/FindByTrashed"
)

// ShippingQueryServiceClient is the client API for ShippingQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShippingQueryServiceClient interface {
	FindAll(ctx context.Context, in *FindAllShippingRequest, opts ...grpc.CallOption) (*ApiResponsePaginationShipping, error)
	FindById(ctx context.Context, in *FindByIdShippingRequest, opts ...grpc.CallOption) (*ApiResponseShipping, error)
	FindByOrder(ctx context.Context, in *FindByIdShippingRequest, opts ...grpc.CallOption) (*ApiResponseShipping, error)
	FindByActive(ctx context.Context, in *FindAllShippingRequest, opts ...grpc.CallOption) (*ApiResponsePaginationShippingDeleteAt, error)
	FindByTrashed(ctx context.Context, in *FindAllShippingRequest, opts ...grpc.CallOption) (*ApiResponsePaginationShippingDeleteAt, error)
}

type shippingQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShippingQueryServiceClient(cc grpc.ClientConnInterface) ShippingQueryServiceClient {
	return &shippingQueryServiceClient{cc}
}

func (c *shippingQueryServiceClient) FindAll(ctx context.Context, in *FindAllShippingRequest, opts ...grpc.CallOption) (*ApiResponsePaginationShipping, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationShipping)
	err := c.cc.Invoke(ctx, ShippingQueryService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingQueryServiceClient) FindById(ctx context.Context, in *FindByIdShippingRequest, opts ...grpc.CallOption) (*ApiResponseShipping, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseShipping)
	err := c.cc.Invoke(ctx, ShippingQueryService_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingQueryServiceClient) FindByOrder(ctx context.Context, in *FindByIdShippingRequest, opts ...grpc.CallOption) (*ApiResponseShipping, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseShipping)
	err := c.cc.Invoke(ctx, ShippingQueryService_FindByOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingQueryServiceClient) FindByActive(ctx context.Context, in *FindAllShippingRequest, opts ...grpc.CallOption) (*ApiResponsePaginationShippingDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationShippingDeleteAt)
	err := c.cc.Invoke(ctx, ShippingQueryService_FindByActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingQueryServiceClient) FindByTrashed(ctx context.Context, in *FindAllShippingRequest, opts ...grpc.CallOption) (*ApiResponsePaginationShippingDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationShippingDeleteAt)
	err := c.cc.Invoke(ctx, ShippingQueryService_FindByTrashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingQueryServiceServer is the server API for ShippingQueryService service.
// All implementations must embed UnimplementedShippingQueryServiceServer
// for forward compatibility.
type ShippingQueryServiceServer interface {
	FindAll(context.Context, *FindAllShippingRequest) (*ApiResponsePaginationShipping, error)
	FindById(context.Context, *FindByIdShippingRequest) (*ApiResponseShipping, error)
	FindByOrder(context.Context, *FindByIdShippingRequest) (*ApiResponseShipping, error)
	FindByActive(context.Context, *FindAllShippingRequest) (*ApiResponsePaginationShippingDeleteAt, error)
	FindByTrashed(context.Context, *FindAllShippingRequest) (*ApiResponsePaginationShippingDeleteAt, error)
	mustEmbedUnimplementedShippingQueryServiceServer()
}

// UnimplementedShippingQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShippingQueryServiceServer struct{}

func (UnimplementedShippingQueryServiceServer) FindAll(context.Context, *FindAllShippingRequest) (*ApiResponsePaginationShipping, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedShippingQueryServiceServer) FindById(context.Context, *FindByIdShippingRequest) (*ApiResponseShipping, error) {
	return nil, status.Error(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedShippingQueryServiceServer) FindByOrder(context.Context, *FindByIdShippingRequest) (*ApiResponseShipping, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByOrder not implemented")
}
func (UnimplementedShippingQueryServiceServer) FindByActive(context.Context, *FindAllShippingRequest) (*ApiResponsePaginationShippingDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByActive not implemented")
}
func (UnimplementedShippingQueryServiceServer) FindByTrashed(context.Context, *FindAllShippingRequest) (*ApiResponsePaginationShippingDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByTrashed not implemented")
}
func (UnimplementedShippingQueryServiceServer) mustEmbedUnimplementedShippingQueryServiceServer() {}
func (UnimplementedShippingQueryServiceServer) testEmbeddedByValue()                              {}

// UnsafeShippingQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShippingQueryServiceServer will
// result in compilation errors.
type UnsafeShippingQueryServiceServer interface {
	mustEmbedUnimplementedShippingQueryServiceServer()
}

func RegisterShippingQueryServiceServer(s grpc.ServiceRegistrar, srv ShippingQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedShippingQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShippingQueryService_ServiceDesc, srv)
}

func _ShippingQueryService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllShippingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingQueryServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingQueryService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingQueryServiceServer).FindAll(ctx, req.(*FindAllShippingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingQueryService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdShippingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingQueryServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingQueryService_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingQueryServiceServer).FindById(ctx, req.(*FindByIdShippingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingQueryService_FindByOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdShippingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingQueryServiceServer).FindByOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingQueryService_FindByOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingQueryServiceServer).FindByOrder(ctx, req.(*FindByIdShippingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingQueryService_FindByActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllShippingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingQueryServiceServer).FindByActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingQueryService_FindByActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingQueryServiceServer).FindByActive(ctx, req.(*FindAllShippingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingQueryService_FindByTrashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllShippingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingQueryServiceServer).FindByTrashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingQueryService_FindByTrashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingQueryServiceServer).FindByTrashed(ctx, req.(*FindAllShippingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShippingQueryService_ServiceDesc is the grpc.ServiceDesc for ShippingQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShippingQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.shipping_address.ShippingQueryService",
	HandlerType: (*ShippingQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _ShippingQueryService_FindAll_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _ShippingQueryService_FindById_Handler,
		},
		{
			MethodName: "FindByOrder",
			Handler:    _ShippingQueryService_FindByOrder_Handler,
		},
		{
			MethodName: "FindByActive",
			Handler:    _ShippingQueryService_FindByActive_Handler,
		},
		{
			MethodName: "FindByTrashed",
			Handler:    _ShippingQueryService_FindByTrashed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipping_address/shipping_address_query.proto",
}
