// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shipping_address/shipping_address_command.proto

package shipping_address

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShippingAddressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Alamat         string                 `protobuf:"bytes,2,opt,name=alamat,proto3" json:"alamat,omitempty"`
	Provinsi       string                 `protobuf:"bytes,3,opt,name=provinsi,proto3" json:"provinsi,omitempty"`
	Kota           string                 `protobuf:"bytes,4,opt,name=kota,proto3" json:"kota,omitempty"`
	Courier        string                 `protobuf:"bytes,5,opt,name=courier,proto3" json:"courier,omitempty"`
	ShippingMethod string                 `protobuf:"bytes,6,opt,name=shipping_method,json=shippingMethod,proto3" json:"shipping_method,omitempty"`
	ShippingCost   int32                  `protobuf:"varint,7,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	Negara         string                 `protobuf:"bytes,8,opt,name=negara,proto3" json:"negara,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateShippingAddressRequest) Reset() {
	*x = CreateShippingAddressRequest{}
	mi := &file_shipping_address_shipping_address_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShippingAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShippingAddressRequest) ProtoMessage() {}

func (x *CreateShippingAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_shipping_address_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShippingAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateShippingAddressRequest) Descriptor() ([]byte, []int) {
	return file_shipping_address_shipping_address_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShippingAddressRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateShippingAddressRequest) GetAlamat() string {
	if x != nil {
		return x.Alamat
	}
	return ""
}

func (x *CreateShippingAddressRequest) GetProvinsi() string {
	if x != nil {
		return x.Provinsi
	}
	return ""
}

func (x *CreateShippingAddressRequest) GetKota() string {
	if x != nil {
		return x.Kota
	}
	return ""
}

func (x *CreateShippingAddressRequest) GetCourier() string {
	if x != nil {
		return x.Courier
	}
	return ""
}

func (x *CreateShippingAddressRequest) GetShippingMethod() string {
	if x != nil {
		return x.ShippingMethod
	}
	return ""
}

func (x *CreateShippingAddressRequest) GetShippingCost() int32 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *CreateShippingAddressRequest) GetNegara() string {
	if x != nil {
		return x.Negara
	}
	return ""
}

type UpdateShippingAddressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShippingId     int32                  `protobuf:"varint,1,opt,name=shipping_id,json=shippingId,proto3" json:"shipping_id,omitempty"`
	OrderId        int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Alamat         string                 `protobuf:"bytes,3,opt,name=alamat,proto3" json:"alamat,omitempty"`
	Provinsi       string                 `protobuf:"bytes,4,opt,name=provinsi,proto3" json:"provinsi,omitempty"`
	Kota           string                 `protobuf:"bytes,5,opt,name=kota,proto3" json:"kota,omitempty"`
	Courier        string                 `protobuf:"bytes,6,opt,name=courier,proto3" json:"courier,omitempty"`
	ShippingMethod string                 `protobuf:"bytes,7,opt,name=shipping_method,json=shippingMethod,proto3" json:"shipping_method,omitempty"`
	ShippingCost   int32                  `protobuf:"varint,8,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	Negara         string                 `protobuf:"bytes,9,opt,name=negara,proto3" json:"negara,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateShippingAddressRequest) Reset() {
	*x = UpdateShippingAddressRequest{}
	mi := &file_shipping_address_shipping_address_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShippingAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShippingAddressRequest) ProtoMessage() {}

func (x *UpdateShippingAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_shipping_address_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShippingAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateShippingAddressRequest) Descriptor() ([]byte, []int) {
	return file_shipping_address_shipping_address_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateShippingAddressRequest) GetShippingId() int32 {
	if x != nil {
		return x.ShippingId
	}
	return 0
}

func (x *UpdateShippingAddressRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateShippingAddressRequest) GetAlamat() string {
	if x != nil {
		return x.Alamat
	}
	return ""
}

func (x *UpdateShippingAddressRequest) GetProvinsi() string {
	if x != nil {
		return x.Provinsi
	}
	return ""
}

func (x *UpdateShippingAddressRequest) GetKota() string {
	if x != nil {
		return x.Kota
	}
	return ""
}

func (x *UpdateShippingAddressRequest) GetCourier() string {
	if x != nil {
		return x.Courier
	}
	return ""
}

func (x *UpdateShippingAddressRequest) GetShippingMethod() string {
	if x != nil {
		return x.ShippingMethod
	}
	return ""
}

func (x *UpdateShippingAddressRequest) GetShippingCost() int32 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *UpdateShippingAddressRequest) GetNegara() string {
	if x != nil {
		return x.Negara
	}
	return ""
}

var File_shipping_address_shipping_address_command_proto protoreflect.FileDescriptor

const file_shipping_address_shipping_address_command_proto_rawDesc = "" +
	"\n" +
	"/shipping_address/shipping_address_command.proto\x12\x13pb.shipping_address\x1a\x1bgoogle/protobuf/empty.proto\x1a.shipping_address/shipping_address_common.proto\"\x81\x02\n" +
	"\x1cCreateShippingAddressRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12\x16\n" +
	"\x06alamat\x18\x02 \x01(\tR\x06alamat\x12\x1a\n" +
	"\bprovinsi\x18\x03 \x01(\tR\bprovinsi\x12\x12\n" +
	"\x04kota\x18\x04 \x01(\tR\x04kota\x12\x18\n" +
	"\acourier\x18\x05 \x01(\tR\acourier\x12'\n" +
	"\x0fshipping_method\x18\x06 \x01(\tR\x0eshippingMethod\x12#\n" +
	"\rshipping_cost\x18\a \x01(\x05R\fshippingCost\x12\x16\n" +
	"\x06negara\x18\b \x01(\tR\x06negara\"\xa2\x02\n" +
	"\x1cUpdateShippingAddressRequest\x12\x1f\n" +
	"\vshipping_id\x18\x01 \x01(\x05R\n" +
	"shippingId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x16\n" +
	"\x06alamat\x18\x03 \x01(\tR\x06alamat\x12\x1a\n" +
	"\bprovinsi\x18\x04 \x01(\tR\bprovinsi\x12\x12\n" +
	"\x04kota\x18\x05 \x01(\tR\x04kota\x12\x18\n" +
	"\acourier\x18\x06 \x01(\tR\acourier\x12'\n" +
	"\x0fshipping_method\x18\a \x01(\tR\x0eshippingMethod\x12#\n" +
	"\rshipping_cost\x18\b \x01(\x05R\fshippingCost\x12\x16\n" +
	"\x06negara\x18\t \x01(\tR\x06negara2\x93\a\n" +
	"\x16ShippingCommandService\x12m\n" +
	"\x0eCreateShipping\x121.pb.shipping_address.CreateShippingAddressRequest\x1a(.pb.shipping_address.ApiResponseShipping\x12m\n" +
	"\x0eUpdateShipping\x121.pb.shipping_address.UpdateShippingAddressRequest\x1a(.pb.shipping_address.ApiResponseShipping\x12q\n" +
	"\x0fTrashedShipping\x12,.pb.shipping_address.FindByIdShippingRequest\x1a0.pb.shipping_address.ApiResponseShippingDeleteAt\x12q\n" +
	"\x0fRestoreShipping\x12,.pb.shipping_address.FindByIdShippingRequest\x1a0.pb.shipping_address.ApiResponseShippingDeleteAt\x12w\n" +
	"\x17DeleteShippingPermanent\x12,.pb.shipping_address.FindByIdShippingRequest\x1a..pb.shipping_address.ApiResponseShippingDelete\x12Y\n" +
	"\x12RestoreAllShipping\x12\x16.google.protobuf.Empty\x1a+.pb.shipping_address.ApiResponseShippingAll\x12~\n" +
	"\x1eDeleteShippingByOrderPermanent\x12,.pb.shipping_address.FindByIdShippingRequest\x1a..pb.shipping_address.ApiResponseShippingDelete\x12a\n" +
	"\x1aDeleteAllShippingPermanent\x12\x16.google.protobuf.Empty\x1a+.pb.shipping_address.ApiResponseShippingAllBFZDgithub.com/MamangRust/monolith-graphql-ecommerce-pb/shipping_addressb\x06proto3"

var (
	file_shipping_address_shipping_address_command_proto_rawDescOnce sync.Once
	file_shipping_address_shipping_address_command_proto_rawDescData []byte
)

func file_shipping_address_shipping_address_command_proto_rawDescGZIP() []byte {
	file_shipping_address_shipping_address_command_proto_rawDescOnce.Do(func() {
		file_shipping_address_shipping_address_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_address_shipping_address_command_proto_rawDesc), len(file_shipping_address_shipping_address_command_proto_rawDesc)))
	})
	return file_shipping_address_shipping_address_command_proto_rawDescData
}

var file_shipping_address_shipping_address_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shipping_address_shipping_address_command_proto_goTypes = []any{
	(*CreateShippingAddressRequest)(nil), // 0: pb.shipping_address.CreateShippingAddressRequest
	(*UpdateShippingAddressRequest)(nil), // 1: pb.shipping_address.UpdateShippingAddressRequest
	(*FindByIdShippingRequest)(nil),      // 2: pb.shipping_address.FindByIdShippingRequest
	(*emptypb.Empty)(nil),                // 3: google.protobuf.Empty
	(*ApiResponseShipping)(nil),          // 4: pb.shipping_address.ApiResponseShipping
	(*ApiResponseShippingDeleteAt)(nil),  // 5: pb.shipping_address.ApiResponseShippingDeleteAt
	(*ApiResponseShippingDelete)(nil),    // 6: pb.shipping_address.ApiResponseShippingDelete
	(*ApiResponseShippingAll)(nil),       // 7: pb.shipping_address.ApiResponseShippingAll
}
var file_shipping_address_shipping_address_command_proto_depIdxs = []int32{
	0, // 0: pb.shipping_address.ShippingCommandService.CreateShipping:input_type -> pb.shipping_address.CreateShippingAddressRequest
	1, // 1: pb.shipping_address.ShippingCommandService.UpdateShipping:input_type -> pb.shipping_address.UpdateShippingAddressRequest
	2, // 2: pb.shipping_address.ShippingCommandService.TrashedShipping:input_type -> pb.shipping_address.FindByIdShippingRequest
	2, // 3: pb.shipping_address.ShippingCommandService.RestoreShipping:input_type -> pb.shipping_address.FindByIdShippingRequest
	2, // 4: pb.shipping_address.ShippingCommandService.DeleteShippingPermanent:input_type -> pb.shipping_address.FindByIdShippingRequest
	3, // 5: pb.shipping_address.ShippingCommandService.RestoreAllShipping:input_type -> google.protobuf.Empty
	2, // 6: pb.shipping_address.ShippingCommandService.DeleteShippingByOrderPermanent:input_type -> pb.shipping_address.FindByIdShippingRequest
	3, // 7: pb.shipping_address.ShippingCommandService.DeleteAllShippingPermanent:input_type -> google.protobuf.Empty
	4, // 8: pb.shipping_address.ShippingCommandService.CreateShipping:output_type -> pb.shipping_address.ApiResponseShipping
	4, // 9: pb.shipping_address.ShippingCommandService.UpdateShipping:output_type -> pb.shipping_address.ApiResponseShipping
	5, // 10: pb.shipping_address.ShippingCommandService.TrashedShipping:output_type -> pb.shipping_address.ApiResponseShippingDeleteAt
	5, // 11: pb.shipping_address.ShippingCommandService.RestoreShipping:output_type -> pb.shipping_address.ApiResponseShippingDeleteAt
	6, // 12: pb.shipping_address.ShippingCommandService.DeleteShippingPermanent:output_type -> pb.shipping_address.ApiResponseShippingDelete
	7, // 13: pb.shipping_address.ShippingCommandService.RestoreAllShipping:output_type -> pb.shipping_address.ApiResponseShippingAll
	6, // 14: pb.shipping_address.ShippingCommandService.DeleteShippingByOrderPermanent:output_type -> pb.shipping_address.ApiResponseShippingDelete
	7, // 15: pb.shipping_address.ShippingCommandService.DeleteAllShippingPermanent:output_type -> pb.shipping_address.ApiResponseShippingAll
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shipping_address_shipping_address_command_proto_init() }
func file_shipping_address_shipping_address_command_proto_init() {
	if File_shipping_address_shipping_address_command_proto != nil {
		return
	}
	file_shipping_address_shipping_address_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_address_shipping_address_command_proto_rawDesc), len(file_shipping_address_shipping_address_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_address_shipping_address_command_proto_goTypes,
		DependencyIndexes: file_shipping_address_shipping_address_command_proto_depIdxs,
		MessageInfos:      file_shipping_address_shipping_address_command_proto_msgTypes,
	}.Build()
	File_shipping_address_shipping_address_command_proto = out.File
	file_shipping_address_shipping_address_command_proto_goTypes = nil
	file_shipping_address_shipping_address_command_proto_depIdxs = nil
}
