// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: merchant_detail/merchant_detail_command.proto

package merchant_detail

import (
	context "context"
	merchant "github.com/MamangRust/monolith-graphql-ecommerce-pb/merchant"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantDetailCommandService_Create_FullMethodName                           = "/pb.merchant_detail.MerchantDetailCommandService/Create"
	MerchantDetailCommandService_Update_FullMethodName                           = "/pb.merchant_detail.MerchantDetailCommandService/Update"
	MerchantDetailCommandService_TrashedMerchantDetail_FullMethodName            = "/pb.merchant_detail.MerchantDetailCommandService/TrashedMerchantDetail"
	MerchantDetailCommandService_RestoreMerchantDetail_FullMethodName            = "/pb.merchant_detail.MerchantDetailCommandService/RestoreMerchantDetail"
	MerchantDetailCommandService_DeleteMerchantDetailPermanent_FullMethodName    = "/pb.merchant_detail.MerchantDetailCommandService/DeleteMerchantDetailPermanent"
	MerchantDetailCommandService_RestoreAllMerchantDetail_FullMethodName         = "/pb.merchant_detail.MerchantDetailCommandService/RestoreAllMerchantDetail"
	MerchantDetailCommandService_DeleteAllMerchantDetailPermanent_FullMethodName = "/pb.merchant_detail.MerchantDetailCommandService/DeleteAllMerchantDetailPermanent"
)

// MerchantDetailCommandServiceClient is the client API for MerchantDetailCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantDetailCommandServiceClient interface {
	Create(ctx context.Context, in *CreateMerchantDetailRequest, opts ...grpc.CallOption) (*ApiResponseMerchantDetail, error)
	Update(ctx context.Context, in *UpdateMerchantDetailRequest, opts ...grpc.CallOption) (*ApiResponseMerchantDetail, error)
	TrashedMerchantDetail(ctx context.Context, in *FindByIdMerchantDetailRequest, opts ...grpc.CallOption) (*ApiResponseMerchantDetailDeleteAt, error)
	RestoreMerchantDetail(ctx context.Context, in *FindByIdMerchantDetailRequest, opts ...grpc.CallOption) (*ApiResponseMerchantDetailDeleteAt, error)
	DeleteMerchantDetailPermanent(ctx context.Context, in *FindByIdMerchantDetailRequest, opts ...grpc.CallOption) (*merchant.ApiResponseMerchantDelete, error)
	RestoreAllMerchantDetail(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*merchant.ApiResponseMerchantAll, error)
	DeleteAllMerchantDetailPermanent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*merchant.ApiResponseMerchantAll, error)
}

type merchantDetailCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantDetailCommandServiceClient(cc grpc.ClientConnInterface) MerchantDetailCommandServiceClient {
	return &merchantDetailCommandServiceClient{cc}
}

func (c *merchantDetailCommandServiceClient) Create(ctx context.Context, in *CreateMerchantDetailRequest, opts ...grpc.CallOption) (*ApiResponseMerchantDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantDetail)
	err := c.cc.Invoke(ctx, MerchantDetailCommandService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantDetailCommandServiceClient) Update(ctx context.Context, in *UpdateMerchantDetailRequest, opts ...grpc.CallOption) (*ApiResponseMerchantDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantDetail)
	err := c.cc.Invoke(ctx, MerchantDetailCommandService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantDetailCommandServiceClient) TrashedMerchantDetail(ctx context.Context, in *FindByIdMerchantDetailRequest, opts ...grpc.CallOption) (*ApiResponseMerchantDetailDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantDetailDeleteAt)
	err := c.cc.Invoke(ctx, MerchantDetailCommandService_TrashedMerchantDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantDetailCommandServiceClient) RestoreMerchantDetail(ctx context.Context, in *FindByIdMerchantDetailRequest, opts ...grpc.CallOption) (*ApiResponseMerchantDetailDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantDetailDeleteAt)
	err := c.cc.Invoke(ctx, MerchantDetailCommandService_RestoreMerchantDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantDetailCommandServiceClient) DeleteMerchantDetailPermanent(ctx context.Context, in *FindByIdMerchantDetailRequest, opts ...grpc.CallOption) (*merchant.ApiResponseMerchantDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(merchant.ApiResponseMerchantDelete)
	err := c.cc.Invoke(ctx, MerchantDetailCommandService_DeleteMerchantDetailPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantDetailCommandServiceClient) RestoreAllMerchantDetail(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*merchant.ApiResponseMerchantAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(merchant.ApiResponseMerchantAll)
	err := c.cc.Invoke(ctx, MerchantDetailCommandService_RestoreAllMerchantDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantDetailCommandServiceClient) DeleteAllMerchantDetailPermanent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*merchant.ApiResponseMerchantAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(merchant.ApiResponseMerchantAll)
	err := c.cc.Invoke(ctx, MerchantDetailCommandService_DeleteAllMerchantDetailPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantDetailCommandServiceServer is the server API for MerchantDetailCommandService service.
// All implementations must embed UnimplementedMerchantDetailCommandServiceServer
// for forward compatibility.
type MerchantDetailCommandServiceServer interface {
	Create(context.Context, *CreateMerchantDetailRequest) (*ApiResponseMerchantDetail, error)
	Update(context.Context, *UpdateMerchantDetailRequest) (*ApiResponseMerchantDetail, error)
	TrashedMerchantDetail(context.Context, *FindByIdMerchantDetailRequest) (*ApiResponseMerchantDetailDeleteAt, error)
	RestoreMerchantDetail(context.Context, *FindByIdMerchantDetailRequest) (*ApiResponseMerchantDetailDeleteAt, error)
	DeleteMerchantDetailPermanent(context.Context, *FindByIdMerchantDetailRequest) (*merchant.ApiResponseMerchantDelete, error)
	RestoreAllMerchantDetail(context.Context, *emptypb.Empty) (*merchant.ApiResponseMerchantAll, error)
	DeleteAllMerchantDetailPermanent(context.Context, *emptypb.Empty) (*merchant.ApiResponseMerchantAll, error)
	mustEmbedUnimplementedMerchantDetailCommandServiceServer()
}

// UnimplementedMerchantDetailCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantDetailCommandServiceServer struct{}

func (UnimplementedMerchantDetailCommandServiceServer) Create(context.Context, *CreateMerchantDetailRequest) (*ApiResponseMerchantDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedMerchantDetailCommandServiceServer) Update(context.Context, *UpdateMerchantDetailRequest) (*ApiResponseMerchantDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedMerchantDetailCommandServiceServer) TrashedMerchantDetail(context.Context, *FindByIdMerchantDetailRequest) (*ApiResponseMerchantDetailDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method TrashedMerchantDetail not implemented")
}
func (UnimplementedMerchantDetailCommandServiceServer) RestoreMerchantDetail(context.Context, *FindByIdMerchantDetailRequest) (*ApiResponseMerchantDetailDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreMerchantDetail not implemented")
}
func (UnimplementedMerchantDetailCommandServiceServer) DeleteMerchantDetailPermanent(context.Context, *FindByIdMerchantDetailRequest) (*merchant.ApiResponseMerchantDelete, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMerchantDetailPermanent not implemented")
}
func (UnimplementedMerchantDetailCommandServiceServer) RestoreAllMerchantDetail(context.Context, *emptypb.Empty) (*merchant.ApiResponseMerchantAll, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreAllMerchantDetail not implemented")
}
func (UnimplementedMerchantDetailCommandServiceServer) DeleteAllMerchantDetailPermanent(context.Context, *emptypb.Empty) (*merchant.ApiResponseMerchantAll, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAllMerchantDetailPermanent not implemented")
}
func (UnimplementedMerchantDetailCommandServiceServer) mustEmbedUnimplementedMerchantDetailCommandServiceServer() {
}
func (UnimplementedMerchantDetailCommandServiceServer) testEmbeddedByValue() {}

// UnsafeMerchantDetailCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantDetailCommandServiceServer will
// result in compilation errors.
type UnsafeMerchantDetailCommandServiceServer interface {
	mustEmbedUnimplementedMerchantDetailCommandServiceServer()
}

func RegisterMerchantDetailCommandServiceServer(s grpc.ServiceRegistrar, srv MerchantDetailCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedMerchantDetailCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantDetailCommandService_ServiceDesc, srv)
}

func _MerchantDetailCommandService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMerchantDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantDetailCommandServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantDetailCommandService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantDetailCommandServiceServer).Create(ctx, req.(*CreateMerchantDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantDetailCommandService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMerchantDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantDetailCommandServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantDetailCommandService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantDetailCommandServiceServer).Update(ctx, req.(*UpdateMerchantDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantDetailCommandService_TrashedMerchantDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdMerchantDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantDetailCommandServiceServer).TrashedMerchantDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantDetailCommandService_TrashedMerchantDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantDetailCommandServiceServer).TrashedMerchantDetail(ctx, req.(*FindByIdMerchantDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantDetailCommandService_RestoreMerchantDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdMerchantDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantDetailCommandServiceServer).RestoreMerchantDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantDetailCommandService_RestoreMerchantDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantDetailCommandServiceServer).RestoreMerchantDetail(ctx, req.(*FindByIdMerchantDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantDetailCommandService_DeleteMerchantDetailPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdMerchantDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantDetailCommandServiceServer).DeleteMerchantDetailPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantDetailCommandService_DeleteMerchantDetailPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantDetailCommandServiceServer).DeleteMerchantDetailPermanent(ctx, req.(*FindByIdMerchantDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantDetailCommandService_RestoreAllMerchantDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantDetailCommandServiceServer).RestoreAllMerchantDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantDetailCommandService_RestoreAllMerchantDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantDetailCommandServiceServer).RestoreAllMerchantDetail(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantDetailCommandService_DeleteAllMerchantDetailPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantDetailCommandServiceServer).DeleteAllMerchantDetailPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantDetailCommandService_DeleteAllMerchantDetailPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantDetailCommandServiceServer).DeleteAllMerchantDetailPermanent(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantDetailCommandService_ServiceDesc is the grpc.ServiceDesc for MerchantDetailCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantDetailCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.merchant_detail.MerchantDetailCommandService",
	HandlerType: (*MerchantDetailCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _MerchantDetailCommandService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MerchantDetailCommandService_Update_Handler,
		},
		{
			MethodName: "TrashedMerchantDetail",
			Handler:    _MerchantDetailCommandService_TrashedMerchantDetail_Handler,
		},
		{
			MethodName: "RestoreMerchantDetail",
			Handler:    _MerchantDetailCommandService_RestoreMerchantDetail_Handler,
		},
		{
			MethodName: "DeleteMerchantDetailPermanent",
			Handler:    _MerchantDetailCommandService_DeleteMerchantDetailPermanent_Handler,
		},
		{
			MethodName: "RestoreAllMerchantDetail",
			Handler:    _MerchantDetailCommandService_RestoreAllMerchantDetail_Handler,
		},
		{
			MethodName: "DeleteAllMerchantDetailPermanent",
			Handler:    _MerchantDetailCommandService_DeleteAllMerchantDetailPermanent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant_detail/merchant_detail_command.proto",
}
