package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	sharedErrors "github.com/MamangRust/monolith-ecommerce-shared/errors"
	graphqlerror "github.com/MamangRust/monolith-graphql-ecommerce-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-ecommerce-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-graphql-ecommerce-pb"
)

// CreateMerchantSocialLink is the resolver for the createMerchantSocialLink field.
func (r *mutationResolver) CreateMerchantSocialLink(ctx context.Context, input *model.CreateMerchantSocialInput) (*model.APIResponseMerchantSocialMediaLink, error) {
	return ResolverHandle(r.ResolverHandle, "CreateMerchantSocialLink", ctx, func(ctx context.Context) (*model.APIResponseMerchantSocialMediaLink, error) {
		id := int(input.MerchantDetailID)

		if id == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant detail ID cannot be zero"))
		}

		socialLinks := make([]*pb.MerchantSocialLinkInput, 0)
		for _, link := range input.SocialLinks {
			socialLinks = append(socialLinks, &pb.MerchantSocialLinkInput{
				Platform: link.Platform,
				Url:      link.URL,
			})
		}

		req := &pb.CreateMerchantSocialInput{
			MerchantDetailId: int32(input.MerchantDetailID),
			SocialLinks:      socialLinks,
		}

		res, err := r.MerchantSocialLinkGraphql.MerchantSocialLinkClient.CreateMerchantSocialLink(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateMerchantSocialLink")
		}

		so := r.MerchantSocialLinkGraphql.Mapping.ToGraphqlResponseMerchantSocialLink(res)

		return so, nil
	})
}

// UpdateMerchantSocialLink is the resolver for the updateMerchantSocialLink field.
func (r *mutationResolver) UpdateMerchantSocialLink(ctx context.Context, input *model.UpdateMerchantSocialInput) (*model.APIResponseMerchantSocialMediaLink, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateMerchantSocialLink", ctx, func(ctx context.Context) (*model.APIResponseMerchantSocialMediaLink, error) {
		if input.MerchantDetailID == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant detail ID cannot be zero"))
		}

		socialLinks := make([]*pb.MerchantSocialLinkInput, 0)
		for _, link := range input.SocialLinks {
			socialLinks = append(socialLinks, &pb.MerchantSocialLinkInput{
				Platform: link.Platform,
				Url:      link.URL,
			})
		}

		req := &pb.UpdateMerchantSocialInput{
			MerchantDetailId: int32(input.MerchantDetailID),
			SocialLinks:      socialLinks,
		}

		res, err := r.MerchantSocialLinkGraphql.MerchantSocialLinkClient.UpdateMerchantSocialLink(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateMerchantSocialLink")
		}

		so := r.MerchantSocialLinkGraphql.Mapping.ToGraphqlResponseMerchantSocialLink(res)

		return so, nil
	})
}
