package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	graphqlerror "github.com/MamangRust/monolith-graphql-ecommerce-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-ecommerce-apigateway/internal/model"
	pbmerchant "github.com/MamangRust/monolith-graphql-ecommerce-pb/merchant"
	pb "github.com/MamangRust/monolith-graphql-ecommerce-pb/merchant_detail"
	sharedErrors "github.com/MamangRust/monolith-graphql-ecommerce-shared/errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateMerchantDetail is the resolver for the createMerchantDetail field.
func (r *mutationResolver) CreateMerchantDetail(ctx context.Context, input model.CreateMerchantDetailInput) (*model.APIResponseMerchantDetail, error) {
	return ResolverHandle[*model.APIResponseMerchantDetail](
		r.ResolverHandle,
		"CreateMerchantDetail",
		ctx,
		func(ctx context.Context) (*model.APIResponseMerchantDetail, error) {

			coverPath, err := r.saveImageDetail(
				&input.CoverImage,
				"cover",
				"uploads/merchant/cover",
			)
			if err != nil {
				return nil, err
			}

			logoPath, err := r.saveImageDetail(
				&input.Logo,
				"logo",
				"uploads/merchant/logo",
			)
			if err != nil {
				return nil, err
			}

			req := &pb.CreateMerchantDetailRequest{
				MerchantId:       int32(input.MerchantID),
				DisplayName:      input.DisplayName,
				CoverImageUrl:    coverPath,
				LogoUrl:          logoPath,
				ShortDescription: input.ShortDescription,
				WebsiteUrl:       input.WebsiteURL,
			}

			res, err := r.MerchantDetailGraphql.MerchantDetailCommandClient.Create(ctx, req)
			if err != nil {
				return nil, r.handleGraphQLError(err, "CreateMerchantDetail")
			}

			return r.MerchantDetailGraphql.
				Mapping.
				ToGraphqlResponseMerchantDetail(res), nil
		},
	)
}

// UpdateMerchantDetail is the resolver for the updateMerchantDetail field.
func (r *mutationResolver) UpdateMerchantDetail(ctx context.Context, input model.UpdateMerchantDetailInput) (*model.APIResponseMerchantDetail, error) {
	return ResolverHandle[*model.APIResponseMerchantDetail](
		r.ResolverHandle,
		"UpdateMerchantDetail",
		ctx,
		func(ctx context.Context) (*model.APIResponseMerchantDetail, error) {

			id := int32(input.MerchantDetailID)
			if id == 0 {
				return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant detail ID cannot be zero"))
			}

			coverPath, err := r.saveImageDetail(
				&input.CoverImage,
				"cover",
				"uploads/merchant/cover",
			)
			if err != nil {
				return nil, err
			}

			logoPath, err := r.saveImageDetail(
				&input.Logo,
				"logo",
				"uploads/merchant/logo",
			)
			if err != nil {
				return nil, err
			}

			req := &pb.UpdateMerchantDetailRequest{
				MerchantDetailId: id,
				DisplayName:      input.DisplayName,
				CoverImageUrl:    coverPath,
				LogoUrl:          logoPath,
				ShortDescription: input.ShortDescription,
				WebsiteUrl:       input.WebsiteURL,
			}

			res, err := r.MerchantDetailGraphql.MerchantDetailCommandClient.Update(ctx, req)
			if err != nil {
				return nil, r.handleGraphQLError(err, "UpdateMerchantDetail")
			}

			return r.MerchantDetailGraphql.
				Mapping.
				ToGraphqlResponseMerchantDetail(res), nil
		},
	)
}

// TrashMerchantDetail is the resolver for the trashMerchantDetail field.
func (r *mutationResolver) TrashMerchantDetail(ctx context.Context, input model.FindByIDMerchantDetailInput) (*model.APIResponseMerchantDetailDeleteAt, error) {
	return ResolverHandle[*model.APIResponseMerchantDetailDeleteAt](
		r.ResolverHandle,
		"TrashMerchantDetail",
		ctx,
		func(ctx context.Context) (*model.APIResponseMerchantDetailDeleteAt, error) {

			id := int32(input.ID)
			if id == 0 {
				return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant detail ID cannot be zero"))
			}

			res, err := r.MerchantDetailGraphql.MerchantDetailCommandClient.TrashedMerchantDetail(ctx, &pb.FindByIdMerchantDetailRequest{
				Id: id,
			})
			if err != nil {
				return nil, r.handleGraphQLError(err, "TrashMerchantDetail")
			}

			return r.MerchantDetailGraphql.
				Mapping.
				ToGraphqlResponseMerchantDetailDeleteAt(res), nil
		},
	)
}

// RestoreMerchantDetail is the resolver for the restoreMerchantDetail field.
func (r *mutationResolver) RestoreMerchantDetail(ctx context.Context, input model.FindByIDMerchantDetailInput) (*model.APIResponseMerchantDetailDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreMerchantDetail", ctx, func(ctx context.Context) (*model.APIResponseMerchantDetailDeleteAt, error) {
		id := int32(input.ID)

		if id == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant detail ID cannot be zero"))
		}

		result, err := r.MerchantDetailGraphql.MerchantDetailCommandClient.RestoreMerchantDetail(ctx, &pb.FindByIdMerchantDetailRequest{
			Id: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreMerchantDetail")
		}

		so := r.MerchantDetailGraphql.Mapping.ToGraphqlResponseMerchantDetailDeleteAt(result)

		r.MerchantDetailGraphql.Cache.DeleteMerchantDetailCache(ctx, int(id))

		return so, nil
	})
}

// DeleteMerchantDetailPermanent is the resolver for the deleteMerchantDetailPermanent field.
func (r *mutationResolver) DeleteMerchantDetailPermanent(ctx context.Context, input model.FindByIDMerchantDetailInput) (*model.APIResponseMerchantDetailDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteMerchantDetailPermanent", ctx, func(ctx context.Context) (*model.APIResponseMerchantDetailDelete, error) {
		id := int32(input.ID)

		if id == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant detail ID cannot be zero"))
		}

		res, err := r.MerchantDetailGraphql.MerchantDetailCommandClient.DeleteMerchantDetailPermanent(ctx, &pb.FindByIdMerchantDetailRequest{
			Id: id,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteMerchantDetailPermanent")
		}

		so := r.MerchantDetailGraphql.Mapping.ToGraphqlResponseMerchantDetailDelete(res)

		r.MerchantDetailGraphql.Cache.DeleteMerchantDetailCache(ctx, int(id))

		return so, nil
	})
}

// RestoreAllMerchantDetails is the resolver for the restoreAllMerchantDetails field.
func (r *mutationResolver) RestoreAllMerchantDetails(ctx context.Context) (*model.APIResponseMerchantDetailAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllMerchantDetails", ctx, func(ctx context.Context) (*model.APIResponseMerchantDetailAll, error) {
		res, err := r.MerchantDetailGraphql.MerchantDetailCommandClient.RestoreAllMerchantDetail(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllMerchantDetails")
		}

		so := r.MerchantDetailGraphql.Mapping.ToGraphqlResponseMerchantDetailAll(res)

		return so, nil
	})
}

// DeleteAllMerchantDetailsPermanent is the resolver for the deleteAllMerchantDetailsPermanent field.
func (r *mutationResolver) DeleteAllMerchantDetailsPermanent(ctx context.Context) (*model.APIResponseMerchantDetailAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllMerchantDetailsPermanent", ctx, func(ctx context.Context) (*model.APIResponseMerchantDetailAll, error) {
		res, err := r.MerchantDetailGraphql.MerchantDetailCommandClient.DeleteAllMerchantDetailPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllMerchantDetailsPermanent")
		}

		so := r.MerchantDetailGraphql.Mapping.ToGraphqlResponseMerchantDetailAll(res)

		return so, nil
	})
}

// FindAllMerchantDetails is the resolver for the findAllMerchantDetails field.
func (r *queryResolver) FindAllMerchantDetails(ctx context.Context, input model.FindAllMerchantDetailInput) (*model.APIResponsePaginationMerchantDetail, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllMerchantDetails", ctx, func(ctx context.Context) (*model.APIResponsePaginationMerchantDetail, error) {
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		if data, found := r.MerchantDetailGraphql.Cache.GetCachedMerchantDetailAll(ctx, &input); found {
			return data, nil
		}

		reqService := &pbmerchant.FindAllMerchantRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		res, err := r.MerchantDetailGraphql.MerchantDetailQueryClient.FindAll(ctx, reqService)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllMerchantDetails")
		}

		so := r.MerchantDetailGraphql.Mapping.ToGraphqlResponsePaginationMerchantDetail(res)

		r.MerchantDetailGraphql.Cache.SetCachedMerchantDetailAll(ctx, &input, so)

		return so, nil
	})
}

// FindMerchantDetailByID is the resolver for the findMerchantDetailById field.
func (r *queryResolver) FindMerchantDetailByID(ctx context.Context, input model.FindByIDMerchantDetailInput) (*model.APIResponseMerchantDetailRelation, error) {
	return ResolverHandle(r.ResolverHandle, "FindMerchantDetailByID", ctx, func(ctx context.Context) (*model.APIResponseMerchantDetailRelation, error) {
		id := int(input.ID)
		if id == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant detail ID cannot be zero"))
		}

		if data, found := r.MerchantDetailGraphql.Cache.GetCachedMerchantDetailRelation(ctx, id); found {
			return data, nil
		}

		res, err := r.MerchantDetailGraphql.MerchantDetailQueryClient.FindById(ctx, &pb.FindByIdMerchantDetailRequest{
			Id: int32(id),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindMerchantDetailByID")
		}

		so := r.MerchantDetailGraphql.Mapping.ToGraphqlResponseMerchantDetailRelation(res)

		r.MerchantDetailGraphql.Cache.SetCachedMerchantDetailRelation(ctx, id, so)

		return so, nil
	})
}

// FindActiveMerchantDetails is the resolver for the findActiveMerchantDetails field.
func (r *queryResolver) FindActiveMerchantDetails(ctx context.Context, input model.FindAllMerchantDetailInput) (*model.APIResponsePaginationMerchantDetailDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindActiveMerchantDetails", ctx, func(ctx context.Context) (*model.APIResponsePaginationMerchantDetailDeleteAt, error) {
		// Prepare Input Defaults
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		if data, found := r.MerchantDetailGraphql.Cache.GetCachedMerchantDetailActive(ctx, &input); found {
			return data, nil
		}

		reqService := &pbmerchant.FindAllMerchantRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		activeDetails, err := r.MerchantDetailGraphql.MerchantDetailQueryClient.FindByActive(ctx, reqService)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindActiveMerchantDetails")
		}

		so := r.MerchantDetailGraphql.Mapping.ToGraphqlResponsePaginationMerchantDetailDeleteAt(activeDetails)

		r.MerchantDetailGraphql.Cache.SetCachedMerchantDetailActive(ctx, &input, so)

		return so, nil
	})
}

// FindTrashedMerchantDetails is the resolver for the findTrashedMerchantDetails field.
func (r *queryResolver) FindTrashedMerchantDetails(ctx context.Context, input model.FindAllMerchantDetailInput) (*model.APIResponsePaginationMerchantDetailDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindTrashedMerchantDetails", ctx, func(ctx context.Context) (*model.APIResponsePaginationMerchantDetailDeleteAt, error) {
		page := int32(1)
		pageSize := int32(10)
		search := ""

		if input.Page != nil {
			page = int32(*input.Page)
		}
		if input.PageSize != nil {
			pageSize = int32(*input.PageSize)
		}
		if input.Search != nil {
			search = *input.Search
		}

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		if data, found := r.MerchantDetailGraphql.Cache.GetCachedMerchantDetailTrashed(ctx, &input); found {
			return data, nil
		}

		reqService := &pbmerchant.FindAllMerchantRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		}

		res, err := r.MerchantDetailGraphql.MerchantDetailQueryClient.FindByTrashed(ctx, reqService)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindTrashedMerchantDetails")
		}

		so := r.MerchantDetailGraphql.Mapping.ToGraphqlResponsePaginationMerchantDetailDeleteAt(res)

		r.MerchantDetailGraphql.Cache.SetCachedMerchantDetailTrashed(ctx, &input, so)

		return so, nil
	})
}
