package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	graphqlerror "github.com/MamangRust/monolith-graphql-ecommerce-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-ecommerce-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-graphql-ecommerce-pb/merchant_social_link"
	sharedErrors "github.com/MamangRust/monolith-graphql-ecommerce-shared/errors"
)

// CreateMerchantSocialLink is the resolver for the createMerchantSocialLink field.
func (r *mutationResolver) CreateMerchantSocialLink(ctx context.Context, input *model.CreateMerchantSocialInput) (*model.APIResponseMerchantSocialMediaLink, error) {
	return ResolverHandle(r.ResolverHandle, "CreateMerchantSocialLink", ctx, func(ctx context.Context) (*model.APIResponseMerchantSocialMediaLink, error) {
		if input.MerchantDetailID == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant detail ID cannot be zero"))
		}

		var data []*model.MerchantSocialMediaLinkResponse
		var status, message string

		for _, link := range input.SocialLinks {
			req := &pb.CreateMerchantSocialRequest{
				MerchantDetailId: int32(input.MerchantDetailID),
				Platform:         link.Platform,
				Url:              link.URL,
			}

			res, err := r.MerchantSocialLinkGraphql.MerchantSocialLinkClient.Create(ctx, req)
			if err != nil {
				return nil, r.handleGraphQLError(err, "CreateMerchantSocialLink")
			}

			so := r.MerchantSocialLinkGraphql.Mapping.ToGraphqlResponseMerchantSocialLink(res)
			status = so.Status
			message = so.Message
			data = append(data, so.Data...)
		}

		return &model.APIResponseMerchantSocialMediaLink{
			Status:  status,
			Message: message,
			Data:    data,
		}, nil
	})
}

// UpdateMerchantSocialLink is the resolver for the updateMerchantSocialLink field.
func (r *mutationResolver) UpdateMerchantSocialLink(ctx context.Context, input *model.UpdateMerchantSocialInput) (*model.APIResponseMerchantSocialMediaLink, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateMerchantSocialLink", ctx, func(ctx context.Context) (*model.APIResponseMerchantSocialMediaLink, error) {
		if input.MerchantDetailID == 0 {
			return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewBadRequestError("invalid request: merchant detail ID cannot be zero"))
		}

		var data []*model.MerchantSocialMediaLinkResponse
		var status, message string

		for _, link := range input.SocialLinks {
			req := &pb.CreateMerchantSocialRequest{
				MerchantDetailId: int32(input.MerchantDetailID),
				Platform:         link.Platform,
				Url:              link.URL,
			}

			res, err := r.MerchantSocialLinkGraphql.MerchantSocialLinkClient.Create(ctx, req)
			if err != nil {
				return nil, r.handleGraphQLError(err, "UpdateMerchantSocialLink")
			}

			so := r.MerchantSocialLinkGraphql.Mapping.ToGraphqlResponseMerchantSocialLink(res)
			status = so.Status
			message = so.Message
			data = append(data, so.Data...)
		}

		return &model.APIResponseMerchantSocialMediaLink{
			Status:  status,
			Message: message,
			Data:    data,
		}, nil
	})
}
