package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/MamangRust/monolith-ecommerce-shared/domain/requests"
	sharedErrors "github.com/MamangRust/monolith-ecommerce-shared/errors"

	graphqlerror "github.com/MamangRust/monolith-graphql-ecommerce-apigateway/internal/errors"
	"github.com/MamangRust/monolith-graphql-ecommerce-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-graphql-ecommerce-pb"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.APIResponseUserResponse, error) {
	request := &requests.CreateUserRequest{
		FirstName:       input.Firstname,
		LastName:        input.Lastname,
		Email:           input.Email,
		Password:        input.Password,
		ConfirmPassword: input.ConfirmPassword,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.CreateUserRequest{
		Firstname:       input.Firstname,
		Lastname:        input.Lastname,
		Email:           input.Email,
		Password:        input.Password,
		ConfirmPassword: input.ConfirmPassword,
	}

	user, errResp := r.UserGraphql.UserCommandClient.Create(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)

	return so, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.APIResponseUserResponse, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlInvalidUserID
	}

	userId := int(id)
	var password, confirmPassword string
	if input.Password != nil {
		password = *input.Password
	}
	if input.ConfirmPassword != nil {
		confirmPassword = *input.ConfirmPassword
	}

	request := &requests.UpdateUserRequest{
		UserID:          &userId,
		FirstName:       *input.Firstname,
		LastName:        *input.Lastname,
		Email:           *input.Email,
		Password:        password,
		ConfirmPassword: confirmPassword,
	}

	if err := request.Validate(); err != nil {
		validations := r.parseValidationErrors(err)
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(sharedErrors.NewValidationError(validations))
	}

	req := &pb.UpdateUserRequest{
		Id:              id,
		Firstname:       *input.Firstname,
		Lastname:        *input.Lastname,
		Email:           *input.Email,
		Password:        password,
		ConfirmPassword: confirmPassword,
	}

	user, errResp := r.UserGraphql.UserCommandClient.Update(ctx, req)
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)

	return so, nil
}

// TrashedUser is the resolver for the trashedUser field.
func (r *mutationResolver) TrashedUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserResponseDeleteAt, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlUserInvalidId
	}

	user, errResp := r.UserGraphql.UserCommandClient.TrashedUser(ctx, &pb.FindByIdUserRequest{Id: id})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUserDeleteAt(user)

	return so, nil
}

// RestoreUser is the resolver for the restoreUser field.
func (r *mutationResolver) RestoreUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserResponseDeleteAt, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlUserInvalidId
	}

	user, errResp := r.UserGraphql.UserCommandClient.RestoreUser(ctx, &pb.FindByIdUserRequest{Id: id})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUserDeleteAt(user)

	return so, nil
}

// DeleteUserPermanent is the resolver for the deleteUserPermanent field.
func (r *mutationResolver) DeleteUserPermanent(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserDelete, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlUserInvalidId
	}

	res, errResp := r.UserGraphql.UserCommandClient.DeleteUserPermanent(ctx, &pb.FindByIdUserRequest{Id: id})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUserDelete(res)

	return so, nil
}

// RestoreAllUser is the resolver for the restoreAllUser field.
func (r *mutationResolver) RestoreAllUser(ctx context.Context) (*model.APIResponseUserAll, error) {
	res, errResp := r.UserGraphql.UserCommandClient.RestoreAllUser(ctx, &emptypb.Empty{})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUserAll(res)

	return so, nil
}

// DeleteAllUserPermanent is the resolver for the deleteAllUserPermanent field.
func (r *mutationResolver) DeleteAllUserPermanent(ctx context.Context) (*model.APIResponseUserAll, error) {
	res, errResp := r.UserGraphql.UserCommandClient.DeleteAllUserPermanent(ctx, &emptypb.Empty{})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUserAll(res)

	return so, nil
}

// FindAllUsers is the resolver for the findAllUsers field.
func (r *queryResolver) FindAllUsers(ctx context.Context, input *model.FindAllUserInput) (*model.APIResponsePaginationUser, error) {
	panic(fmt.Errorf("not implemented: FindAllUsers - findAllUsers"))
}

// FindByIDUser is the resolver for the findByIdUser field.
func (r *queryResolver) FindByIDUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserResponse, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, graphqlerror.ErrGraphqlInvalidUserID
	}

	user, errResp := r.UserGraphql.UserQueryClient.FindById(ctx, &pb.FindByIdUserRequest{
		Id: id,
	})
	if errResp != nil {
		return nil, graphqlerror.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)

	return so, nil
}

// FindByActiveUsers is the resolver for the findByActiveUsers field.
func (r *queryResolver) FindByActiveUsers(ctx context.Context, input *model.FindAllUserInput) (*model.APIResponsePaginationUserDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByActiveUsers - findByActiveUsers"))
}

// FindByTrashedUsers is the resolver for the findByTrashedUsers field.
func (r *queryResolver) FindByTrashedUsers(ctx context.Context, input *model.FindAllUserInput) (*model.APIResponsePaginationUserDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByTrashedUsers - findByTrashedUsers"))
}
