// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: merchant_policy/merchant_policy_query.proto

package merchant_policy

import (
	context "context"
	merchant "github.com/MamangRust/monolith-graphql-ecommerce-pb/merchant"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantPolicyQueryService_FindAll_FullMethodName       = "/pb.merchant_policy.MerchantPolicyQueryService/FindAll"
	MerchantPolicyQueryService_FindById_FullMethodName      = "/pb.merchant_policy.MerchantPolicyQueryService/FindById"
	MerchantPolicyQueryService_FindByActive_FullMethodName  = "/pb.merchant_policy.MerchantPolicyQueryService/FindByActive"
	MerchantPolicyQueryService_FindByTrashed_FullMethodName = "/pb.merchant_policy.MerchantPolicyQueryService/FindByTrashed"
)

// MerchantPolicyQueryServiceClient is the client API for MerchantPolicyQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantPolicyQueryServiceClient interface {
	FindAll(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantPolicies, error)
	FindById(ctx context.Context, in *FindByIdMerchantPoliciesRequest, opts ...grpc.CallOption) (*ApiResponseMerchantPolicies, error)
	FindByActive(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantPoliciesDeleteAt, error)
	FindByTrashed(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantPoliciesDeleteAt, error)
}

type merchantPolicyQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantPolicyQueryServiceClient(cc grpc.ClientConnInterface) MerchantPolicyQueryServiceClient {
	return &merchantPolicyQueryServiceClient{cc}
}

func (c *merchantPolicyQueryServiceClient) FindAll(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantPolicies, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationMerchantPolicies)
	err := c.cc.Invoke(ctx, MerchantPolicyQueryService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantPolicyQueryServiceClient) FindById(ctx context.Context, in *FindByIdMerchantPoliciesRequest, opts ...grpc.CallOption) (*ApiResponseMerchantPolicies, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantPolicies)
	err := c.cc.Invoke(ctx, MerchantPolicyQueryService_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantPolicyQueryServiceClient) FindByActive(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantPoliciesDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationMerchantPoliciesDeleteAt)
	err := c.cc.Invoke(ctx, MerchantPolicyQueryService_FindByActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantPolicyQueryServiceClient) FindByTrashed(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantPoliciesDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationMerchantPoliciesDeleteAt)
	err := c.cc.Invoke(ctx, MerchantPolicyQueryService_FindByTrashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantPolicyQueryServiceServer is the server API for MerchantPolicyQueryService service.
// All implementations must embed UnimplementedMerchantPolicyQueryServiceServer
// for forward compatibility.
type MerchantPolicyQueryServiceServer interface {
	FindAll(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantPolicies, error)
	FindById(context.Context, *FindByIdMerchantPoliciesRequest) (*ApiResponseMerchantPolicies, error)
	FindByActive(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantPoliciesDeleteAt, error)
	FindByTrashed(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantPoliciesDeleteAt, error)
	mustEmbedUnimplementedMerchantPolicyQueryServiceServer()
}

// UnimplementedMerchantPolicyQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantPolicyQueryServiceServer struct{}

func (UnimplementedMerchantPolicyQueryServiceServer) FindAll(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantPolicies, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedMerchantPolicyQueryServiceServer) FindById(context.Context, *FindByIdMerchantPoliciesRequest) (*ApiResponseMerchantPolicies, error) {
	return nil, status.Error(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedMerchantPolicyQueryServiceServer) FindByActive(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantPoliciesDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByActive not implemented")
}
func (UnimplementedMerchantPolicyQueryServiceServer) FindByTrashed(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantPoliciesDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByTrashed not implemented")
}
func (UnimplementedMerchantPolicyQueryServiceServer) mustEmbedUnimplementedMerchantPolicyQueryServiceServer() {
}
func (UnimplementedMerchantPolicyQueryServiceServer) testEmbeddedByValue() {}

// UnsafeMerchantPolicyQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantPolicyQueryServiceServer will
// result in compilation errors.
type UnsafeMerchantPolicyQueryServiceServer interface {
	mustEmbedUnimplementedMerchantPolicyQueryServiceServer()
}

func RegisterMerchantPolicyQueryServiceServer(s grpc.ServiceRegistrar, srv MerchantPolicyQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedMerchantPolicyQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantPolicyQueryService_ServiceDesc, srv)
}

func _MerchantPolicyQueryService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(merchant.FindAllMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantPolicyQueryServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantPolicyQueryService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantPolicyQueryServiceServer).FindAll(ctx, req.(*merchant.FindAllMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantPolicyQueryService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdMerchantPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantPolicyQueryServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantPolicyQueryService_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantPolicyQueryServiceServer).FindById(ctx, req.(*FindByIdMerchantPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantPolicyQueryService_FindByActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(merchant.FindAllMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantPolicyQueryServiceServer).FindByActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantPolicyQueryService_FindByActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantPolicyQueryServiceServer).FindByActive(ctx, req.(*merchant.FindAllMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantPolicyQueryService_FindByTrashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(merchant.FindAllMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantPolicyQueryServiceServer).FindByTrashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantPolicyQueryService_FindByTrashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantPolicyQueryServiceServer).FindByTrashed(ctx, req.(*merchant.FindAllMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantPolicyQueryService_ServiceDesc is the grpc.ServiceDesc for MerchantPolicyQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantPolicyQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.merchant_policy.MerchantPolicyQueryService",
	HandlerType: (*MerchantPolicyQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _MerchantPolicyQueryService_FindAll_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _MerchantPolicyQueryService_FindById_Handler,
		},
		{
			MethodName: "FindByActive",
			Handler:    _MerchantPolicyQueryService_FindByActive_Handler,
		},
		{
			MethodName: "FindByTrashed",
			Handler:    _MerchantPolicyQueryService_FindByTrashed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant_policy/merchant_policy_query.proto",
}
