// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: merchant_social_link/merchant_social_link_common.proto

package merchant_social_link

import (
	merchant_detail "github.com/MamangRust/monolith-graphql-ecommerce-pb/merchant_detail"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponseMerchantSocial struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	Status        string                                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *merchant_detail.MerchantSocialMediaLinkResponse `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantSocial) Reset() {
	*x = ApiResponseMerchantSocial{}
	mi := &file_merchant_social_link_merchant_social_link_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantSocial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantSocial) ProtoMessage() {}

func (x *ApiResponseMerchantSocial) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_social_link_merchant_social_link_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantSocial.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantSocial) Descriptor() ([]byte, []int) {
	return file_merchant_social_link_merchant_social_link_common_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponseMerchantSocial) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantSocial) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantSocial) GetData() *merchant_detail.MerchantSocialMediaLinkResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_merchant_social_link_merchant_social_link_common_proto protoreflect.FileDescriptor

const file_merchant_social_link_merchant_social_link_common_proto_rawDesc = "" +
	"\n" +
	"6merchant_social_link/merchant_social_link_common.proto\x12\x17pb.merchant_social_link\x1a,merchant_detail/merchant_detail_common.proto\"\x96\x01\n" +
	"\x19ApiResponseMerchantSocial\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\x04data\x18\x03 \x01(\v23.pb.merchant_detail.MerchantSocialMediaLinkResponseR\x04dataBJZHgithub.com/MamangRust/monolith-graphql-ecommerce-pb/merchant_social_linkb\x06proto3"

var (
	file_merchant_social_link_merchant_social_link_common_proto_rawDescOnce sync.Once
	file_merchant_social_link_merchant_social_link_common_proto_rawDescData []byte
)

func file_merchant_social_link_merchant_social_link_common_proto_rawDescGZIP() []byte {
	file_merchant_social_link_merchant_social_link_common_proto_rawDescOnce.Do(func() {
		file_merchant_social_link_merchant_social_link_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_social_link_merchant_social_link_common_proto_rawDesc), len(file_merchant_social_link_merchant_social_link_common_proto_rawDesc)))
	})
	return file_merchant_social_link_merchant_social_link_common_proto_rawDescData
}

var file_merchant_social_link_merchant_social_link_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_merchant_social_link_merchant_social_link_common_proto_goTypes = []any{
	(*ApiResponseMerchantSocial)(nil),                       // 0: pb.merchant_social_link.ApiResponseMerchantSocial
	(*merchant_detail.MerchantSocialMediaLinkResponse)(nil), // 1: pb.merchant_detail.MerchantSocialMediaLinkResponse
}
var file_merchant_social_link_merchant_social_link_common_proto_depIdxs = []int32{
	1, // 0: pb.merchant_social_link.ApiResponseMerchantSocial.data:type_name -> pb.merchant_detail.MerchantSocialMediaLinkResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_merchant_social_link_merchant_social_link_common_proto_init() }
func file_merchant_social_link_merchant_social_link_common_proto_init() {
	if File_merchant_social_link_merchant_social_link_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_social_link_merchant_social_link_common_proto_rawDesc), len(file_merchant_social_link_merchant_social_link_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_merchant_social_link_merchant_social_link_common_proto_goTypes,
		DependencyIndexes: file_merchant_social_link_merchant_social_link_common_proto_depIdxs,
		MessageInfos:      file_merchant_social_link_merchant_social_link_common_proto_msgTypes,
	}.Build()
	File_merchant_social_link_merchant_social_link_common_proto = out.File
	file_merchant_social_link_merchant_social_link_common_proto_goTypes = nil
	file_merchant_social_link_merchant_social_link_common_proto_depIdxs = nil
}
