// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cart/cart_common.proto

package cart

import (
	common "github.com/MamangRust/monolith-graphql-ecommerce-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Weight        int32                  `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_cart_cart_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_cart_cart_common_proto_rawDescGZIP(), []int{0}
}

func (x *CartResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CartResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartResponse) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CartResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CartResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CartResponseDeletedAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Weight        int32                  `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponseDeletedAt) Reset() {
	*x = CartResponseDeletedAt{}
	mi := &file_cart_cart_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponseDeletedAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponseDeletedAt) ProtoMessage() {}

func (x *CartResponseDeletedAt) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponseDeletedAt.ProtoReflect.Descriptor instead.
func (*CartResponseDeletedAt) Descriptor() ([]byte, []int) {
	return file_cart_cart_common_proto_rawDescGZIP(), []int{1}
}

func (x *CartResponseDeletedAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartResponseDeletedAt) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartResponseDeletedAt) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartResponseDeletedAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartResponseDeletedAt) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartResponseDeletedAt) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CartResponseDeletedAt) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartResponseDeletedAt) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CartResponseDeletedAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CartResponseDeletedAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CartResponseDeletedAt) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type ApiResponseCart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CartResponse          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCart) Reset() {
	*x = ApiResponseCart{}
	mi := &file_cart_cart_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCart) ProtoMessage() {}

func (x *ApiResponseCart) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCart.ProtoReflect.Descriptor instead.
func (*ApiResponseCart) Descriptor() ([]byte, []int) {
	return file_cart_cart_common_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseCart) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCart) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCart) GetData() *CartResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCartDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCartDelete) Reset() {
	*x = ApiResponseCartDelete{}
	mi := &file_cart_cart_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCartDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCartDelete) ProtoMessage() {}

func (x *ApiResponseCartDelete) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCartDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseCartDelete) Descriptor() ([]byte, []int) {
	return file_cart_cart_common_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseCartDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCartDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseCartAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCartAll) Reset() {
	*x = ApiResponseCartAll{}
	mi := &file_cart_cart_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCartAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCartAll) ProtoMessage() {}

func (x *ApiResponseCartAll) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCartAll.ProtoReflect.Descriptor instead.
func (*ApiResponseCartAll) Descriptor() ([]byte, []int) {
	return file_cart_cart_common_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponseCartAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCartAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationCart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CartResponse        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMeta `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationCart) Reset() {
	*x = ApiResponsePaginationCart{}
	mi := &file_cart_cart_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationCart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationCart) ProtoMessage() {}

func (x *ApiResponsePaginationCart) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationCart.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationCart) Descriptor() ([]byte, []int) {
	return file_cart_cart_common_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponsePaginationCart) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationCart) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationCart) GetData() []*CartResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationCart) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_cart_cart_common_proto protoreflect.FileDescriptor

const file_cart_cart_common_proto_rawDesc = "" +
	"\n" +
	"\x16cart/cart_common.proto\x12\apb.cart\x1a\x10common/api.proto\"\x88\x02\n" +
	"\fCartResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12\x16\n" +
	"\x06weight\x18\b \x01(\x05R\x06weight\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xb0\x02\n" +
	"\x15CartResponseDeletedAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12\x16\n" +
	"\x06weight\x18\b \x01(\x05R\x06weight\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\v \x01(\tR\tdeletedAt\"n\n" +
	"\x0fApiResponseCart\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.pb.cart.CartResponseR\x04data\"I\n" +
	"\x15ApiResponseCartDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x12ApiResponseCartAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb3\x01\n" +
	"\x19ApiResponsePaginationCart\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.pb.cart.CartResponseR\x04data\x129\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\n" +
	"paginationB:Z8github.com/MamangRust/monolith-graphql-ecommerce-pb/cartb\x06proto3"

var (
	file_cart_cart_common_proto_rawDescOnce sync.Once
	file_cart_cart_common_proto_rawDescData []byte
)

func file_cart_cart_common_proto_rawDescGZIP() []byte {
	file_cart_cart_common_proto_rawDescOnce.Do(func() {
		file_cart_cart_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_cart_common_proto_rawDesc), len(file_cart_cart_common_proto_rawDesc)))
	})
	return file_cart_cart_common_proto_rawDescData
}

var file_cart_cart_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cart_cart_common_proto_goTypes = []any{
	(*CartResponse)(nil),              // 0: pb.cart.CartResponse
	(*CartResponseDeletedAt)(nil),     // 1: pb.cart.CartResponseDeletedAt
	(*ApiResponseCart)(nil),           // 2: pb.cart.ApiResponseCart
	(*ApiResponseCartDelete)(nil),     // 3: pb.cart.ApiResponseCartDelete
	(*ApiResponseCartAll)(nil),        // 4: pb.cart.ApiResponseCartAll
	(*ApiResponsePaginationCart)(nil), // 5: pb.cart.ApiResponsePaginationCart
	(*common.PaginationMeta)(nil),     // 6: pb.common.PaginationMeta
}
var file_cart_cart_common_proto_depIdxs = []int32{
	0, // 0: pb.cart.ApiResponseCart.data:type_name -> pb.cart.CartResponse
	0, // 1: pb.cart.ApiResponsePaginationCart.data:type_name -> pb.cart.CartResponse
	6, // 2: pb.cart.ApiResponsePaginationCart.pagination:type_name -> pb.common.PaginationMeta
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cart_cart_common_proto_init() }
func file_cart_cart_common_proto_init() {
	if File_cart_cart_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_cart_common_proto_rawDesc), len(file_cart_cart_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cart_cart_common_proto_goTypes,
		DependencyIndexes: file_cart_cart_common_proto_depIdxs,
		MessageInfos:      file_cart_cart_common_proto_msgTypes,
	}.Build()
	File_cart_cart_common_proto = out.File
	file_cart_cart_common_proto_goTypes = nil
	file_cart_cart_common_proto_depIdxs = nil
}
