package merchantbusinessapimapper

import (
	"github.com/MamangRust/monolith-graphql-ecommerce-shared/domain/response"

	pbmerchant_business "github.com/MamangRust/monolith-graphql-ecommerce-pb/merchant_business"
)

type MerchantBusinessBaseResponseMapper interface {
	ToResponseMerchantBusiness(merchant *pbmerchant_business.MerchantBusinessResponse) *response.MerchantBusinessResponse
	ToResponsesMerchantBusiness(merchants []*pbmerchant_business.MerchantBusinessResponse) []*response.MerchantBusinessResponse
	ToApiResponseMerchantBusiness(pbResponse *pbmerchant_business.ApiResponseMerchantBusiness) *response.ApiResponseMerchantBusiness
}

type MerchantBusinessQueryResponseMapper interface {
	MerchantBusinessBaseResponseMapper
	ToApiResponsesMerchantBusiness(pbResponse *pbmerchant_business.ApiResponsesMerchantBusiness) *response.ApiResponsesMerchantBusiness
	ToApiResponsePaginationMerchantBusiness(pbResponse *pbmerchant_business.ApiResponsePaginationMerchantBusiness) *response.ApiResponsePaginationMerchantBusiness
	ToApiResponsePaginationMerchantBusinessDeleteAt(pbResponse *pbmerchant_business.ApiResponsePaginationMerchantBusinessDeleteAt) *response.ApiResponsePaginationMerchantBusinessDeleteAt
}

type MerchantBusinessCommandResponseMapper interface {
	MerchantBusinessBaseResponseMapper
	ToResponseMerchantBusinessDeleteAt(merchant *pbmerchant_business.MerchantBusinessResponseDeleteAt) *response.MerchantBusinessResponseDeleteAt
	ToResponsesMerchantBusinessDeleteAt(merchants []*pbmerchant_business.MerchantBusinessResponseDeleteAt) []*response.MerchantBusinessResponseDeleteAt
	ToApiResponseMerchantBusinessDeleteAt(pbResponse *pbmerchant_business.ApiResponseMerchantBusinessDeleteAt) *response.ApiResponseMerchantBusinessDeleteAt
}
