apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: merchant-policy-netpol
  namespace: ecommerce
spec:
  podSelector:
    matchLabels:
      app: merchant-policy
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ecommerce

  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ecommerce

