// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: merchant_award/merchant_award_query.proto

package merchant_award

import (
	merchant "github.com/MamangRust/monolith-graphql-ecommerce-pb/merchant"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_merchant_award_merchant_award_query_proto protoreflect.FileDescriptor

const file_merchant_award_merchant_award_query_proto_rawDesc = "" +
	"\n" +
	")merchant_award/merchant_award_query.proto\x12\x11pb.merchant_award\x1a*merchant_award/merchant_award_common.proto\x1a\x1dmerchant/merchant_query.proto2\xd5\x03\n" +
	"\x19MerchantAwardQueryService\x12e\n" +
	"\aFindAll\x12#.pb.merchant.FindAllMerchantRequest\x1a5.pb.merchant_award.ApiResponsePaginationMerchantAward\x12h\n" +
	"\bFindById\x12/.pb.merchant_award.FindByIdMerchantAwardRequest\x1a+.pb.merchant_award.ApiResponseMerchantAward\x12r\n" +
	"\fFindByActive\x12#.pb.merchant.FindAllMerchantRequest\x1a=.pb.merchant_award.ApiResponsePaginationMerchantAwardDeleteAt\x12s\n" +
	"\rFindByTrashed\x12#.pb.merchant.FindAllMerchantRequest\x1a=.pb.merchant_award.ApiResponsePaginationMerchantAwardDeleteAtBDZBgithub.com/MamangRust/monolith-graphql-ecommerce-pb/merchant_awardb\x06proto3"

var file_merchant_award_merchant_award_query_proto_goTypes = []any{
	(*merchant.FindAllMerchantRequest)(nil),            // 0: pb.merchant.FindAllMerchantRequest
	(*FindByIdMerchantAwardRequest)(nil),               // 1: pb.merchant_award.FindByIdMerchantAwardRequest
	(*ApiResponsePaginationMerchantAward)(nil),         // 2: pb.merchant_award.ApiResponsePaginationMerchantAward
	(*ApiResponseMerchantAward)(nil),                   // 3: pb.merchant_award.ApiResponseMerchantAward
	(*ApiResponsePaginationMerchantAwardDeleteAt)(nil), // 4: pb.merchant_award.ApiResponsePaginationMerchantAwardDeleteAt
}
var file_merchant_award_merchant_award_query_proto_depIdxs = []int32{
	0, // 0: pb.merchant_award.MerchantAwardQueryService.FindAll:input_type -> pb.merchant.FindAllMerchantRequest
	1, // 1: pb.merchant_award.MerchantAwardQueryService.FindById:input_type -> pb.merchant_award.FindByIdMerchantAwardRequest
	0, // 2: pb.merchant_award.MerchantAwardQueryService.FindByActive:input_type -> pb.merchant.FindAllMerchantRequest
	0, // 3: pb.merchant_award.MerchantAwardQueryService.FindByTrashed:input_type -> pb.merchant.FindAllMerchantRequest
	2, // 4: pb.merchant_award.MerchantAwardQueryService.FindAll:output_type -> pb.merchant_award.ApiResponsePaginationMerchantAward
	3, // 5: pb.merchant_award.MerchantAwardQueryService.FindById:output_type -> pb.merchant_award.ApiResponseMerchantAward
	4, // 6: pb.merchant_award.MerchantAwardQueryService.FindByActive:output_type -> pb.merchant_award.ApiResponsePaginationMerchantAwardDeleteAt
	4, // 7: pb.merchant_award.MerchantAwardQueryService.FindByTrashed:output_type -> pb.merchant_award.ApiResponsePaginationMerchantAwardDeleteAt
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_merchant_award_merchant_award_query_proto_init() }
func file_merchant_award_merchant_award_query_proto_init() {
	if File_merchant_award_merchant_award_query_proto != nil {
		return
	}
	file_merchant_award_merchant_award_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_award_merchant_award_query_proto_rawDesc), len(file_merchant_award_merchant_award_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_award_merchant_award_query_proto_goTypes,
		DependencyIndexes: file_merchant_award_merchant_award_query_proto_depIdxs,
	}.Build()
	File_merchant_award_merchant_award_query_proto = out.File
	file_merchant_award_merchant_award_query_proto_goTypes = nil
	file_merchant_award_merchant_award_query_proto_depIdxs = nil
}
