// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: merchant_award/merchant_award_query.proto

package merchant_award

import (
	context "context"
	merchant "github.com/MamangRust/monolith-graphql-ecommerce-pb/merchant"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantAwardQueryService_FindAll_FullMethodName       = "/pb.merchant_award.MerchantAwardQueryService/FindAll"
	MerchantAwardQueryService_FindById_FullMethodName      = "/pb.merchant_award.MerchantAwardQueryService/FindById"
	MerchantAwardQueryService_FindByActive_FullMethodName  = "/pb.merchant_award.MerchantAwardQueryService/FindByActive"
	MerchantAwardQueryService_FindByTrashed_FullMethodName = "/pb.merchant_award.MerchantAwardQueryService/FindByTrashed"
)

// MerchantAwardQueryServiceClient is the client API for MerchantAwardQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantAwardQueryServiceClient interface {
	FindAll(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantAward, error)
	FindById(ctx context.Context, in *FindByIdMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantAward, error)
	FindByActive(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantAwardDeleteAt, error)
	FindByTrashed(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantAwardDeleteAt, error)
}

type merchantAwardQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantAwardQueryServiceClient(cc grpc.ClientConnInterface) MerchantAwardQueryServiceClient {
	return &merchantAwardQueryServiceClient{cc}
}

func (c *merchantAwardQueryServiceClient) FindAll(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantAward, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationMerchantAward)
	err := c.cc.Invoke(ctx, MerchantAwardQueryService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantAwardQueryServiceClient) FindById(ctx context.Context, in *FindByIdMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantAward, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantAward)
	err := c.cc.Invoke(ctx, MerchantAwardQueryService_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantAwardQueryServiceClient) FindByActive(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantAwardDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationMerchantAwardDeleteAt)
	err := c.cc.Invoke(ctx, MerchantAwardQueryService_FindByActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantAwardQueryServiceClient) FindByTrashed(ctx context.Context, in *merchant.FindAllMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationMerchantAwardDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationMerchantAwardDeleteAt)
	err := c.cc.Invoke(ctx, MerchantAwardQueryService_FindByTrashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantAwardQueryServiceServer is the server API for MerchantAwardQueryService service.
// All implementations must embed UnimplementedMerchantAwardQueryServiceServer
// for forward compatibility.
type MerchantAwardQueryServiceServer interface {
	FindAll(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantAward, error)
	FindById(context.Context, *FindByIdMerchantAwardRequest) (*ApiResponseMerchantAward, error)
	FindByActive(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantAwardDeleteAt, error)
	FindByTrashed(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantAwardDeleteAt, error)
	mustEmbedUnimplementedMerchantAwardQueryServiceServer()
}

// UnimplementedMerchantAwardQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantAwardQueryServiceServer struct{}

func (UnimplementedMerchantAwardQueryServiceServer) FindAll(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantAward, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedMerchantAwardQueryServiceServer) FindById(context.Context, *FindByIdMerchantAwardRequest) (*ApiResponseMerchantAward, error) {
	return nil, status.Error(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedMerchantAwardQueryServiceServer) FindByActive(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantAwardDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByActive not implemented")
}
func (UnimplementedMerchantAwardQueryServiceServer) FindByTrashed(context.Context, *merchant.FindAllMerchantRequest) (*ApiResponsePaginationMerchantAwardDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByTrashed not implemented")
}
func (UnimplementedMerchantAwardQueryServiceServer) mustEmbedUnimplementedMerchantAwardQueryServiceServer() {
}
func (UnimplementedMerchantAwardQueryServiceServer) testEmbeddedByValue() {}

// UnsafeMerchantAwardQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantAwardQueryServiceServer will
// result in compilation errors.
type UnsafeMerchantAwardQueryServiceServer interface {
	mustEmbedUnimplementedMerchantAwardQueryServiceServer()
}

func RegisterMerchantAwardQueryServiceServer(s grpc.ServiceRegistrar, srv MerchantAwardQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedMerchantAwardQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantAwardQueryService_ServiceDesc, srv)
}

func _MerchantAwardQueryService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(merchant.FindAllMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAwardQueryServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAwardQueryService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAwardQueryServiceServer).FindAll(ctx, req.(*merchant.FindAllMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantAwardQueryService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdMerchantAwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAwardQueryServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAwardQueryService_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAwardQueryServiceServer).FindById(ctx, req.(*FindByIdMerchantAwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantAwardQueryService_FindByActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(merchant.FindAllMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAwardQueryServiceServer).FindByActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAwardQueryService_FindByActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAwardQueryServiceServer).FindByActive(ctx, req.(*merchant.FindAllMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantAwardQueryService_FindByTrashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(merchant.FindAllMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAwardQueryServiceServer).FindByTrashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAwardQueryService_FindByTrashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAwardQueryServiceServer).FindByTrashed(ctx, req.(*merchant.FindAllMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantAwardQueryService_ServiceDesc is the grpc.ServiceDesc for MerchantAwardQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantAwardQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.merchant_award.MerchantAwardQueryService",
	HandlerType: (*MerchantAwardQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _MerchantAwardQueryService_FindAll_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _MerchantAwardQueryService_FindById_Handler,
		},
		{
			MethodName: "FindByActive",
			Handler:    _MerchantAwardQueryService_FindByActive_Handler,
		},
		{
			MethodName: "FindByTrashed",
			Handler:    _MerchantAwardQueryService_FindByTrashed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant_award/merchant_award_query.proto",
}
