apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
- apigateway/
- auth/
- banner/
- cart/
- category/
- common/
- db-migration/
- email/
- kafka/
- merchant/
- merchant_award/
- merchant_business/
- merchant_detail/
- merchant_policy/
- nginx/
- observability/
- order/
- order_item/
- postgres/
- product/
- redis/
- review/
- review_detail/
- role/
- shipping_address/
- slider/
- transaction/
- user/

patches:
- path: image-pull-secret-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: "^(apigateway|auth|banner|cart|category|email|merchant|merchant-award|merchant-business|merchant-detail|merchant-policy|order|order-item|product|review|review-detail|role|shipping-address|slider|transaction|user)$"
- path: job-image-pull-secret-patch.yaml
  target:
    group: batch
    version: v1
    kind: Job
    name: migrate
