// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: review/review_command.proto

package review

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReviewCommandService_Create_FullMethodName                   = "/pb.review.ReviewCommandService/Create"
	ReviewCommandService_Update_FullMethodName                   = "/pb.review.ReviewCommandService/Update"
	ReviewCommandService_TrashedReview_FullMethodName            = "/pb.review.ReviewCommandService/TrashedReview"
	ReviewCommandService_RestoreReview_FullMethodName            = "/pb.review.ReviewCommandService/RestoreReview"
	ReviewCommandService_DeleteReviewPermanent_FullMethodName    = "/pb.review.ReviewCommandService/DeleteReviewPermanent"
	ReviewCommandService_RestoreAllReview_FullMethodName         = "/pb.review.ReviewCommandService/RestoreAllReview"
	ReviewCommandService_DeleteAllReviewPermanent_FullMethodName = "/pb.review.ReviewCommandService/DeleteAllReviewPermanent"
)

// ReviewCommandServiceClient is the client API for ReviewCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewCommandServiceClient interface {
	Create(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*ApiResponseReview, error)
	Update(ctx context.Context, in *UpdateReviewRequest, opts ...grpc.CallOption) (*ApiResponseReview, error)
	TrashedReview(ctx context.Context, in *FindByIdReviewRequest, opts ...grpc.CallOption) (*ApiResponseReviewDeleteAt, error)
	RestoreReview(ctx context.Context, in *FindByIdReviewRequest, opts ...grpc.CallOption) (*ApiResponseReviewDeleteAt, error)
	DeleteReviewPermanent(ctx context.Context, in *FindByIdReviewRequest, opts ...grpc.CallOption) (*ApiResponseReviewDelete, error)
	RestoreAllReview(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseReviewAll, error)
	DeleteAllReviewPermanent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseReviewAll, error)
}

type reviewCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewCommandServiceClient(cc grpc.ClientConnInterface) ReviewCommandServiceClient {
	return &reviewCommandServiceClient{cc}
}

func (c *reviewCommandServiceClient) Create(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*ApiResponseReview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseReview)
	err := c.cc.Invoke(ctx, ReviewCommandService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewCommandServiceClient) Update(ctx context.Context, in *UpdateReviewRequest, opts ...grpc.CallOption) (*ApiResponseReview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseReview)
	err := c.cc.Invoke(ctx, ReviewCommandService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewCommandServiceClient) TrashedReview(ctx context.Context, in *FindByIdReviewRequest, opts ...grpc.CallOption) (*ApiResponseReviewDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseReviewDeleteAt)
	err := c.cc.Invoke(ctx, ReviewCommandService_TrashedReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewCommandServiceClient) RestoreReview(ctx context.Context, in *FindByIdReviewRequest, opts ...grpc.CallOption) (*ApiResponseReviewDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseReviewDeleteAt)
	err := c.cc.Invoke(ctx, ReviewCommandService_RestoreReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewCommandServiceClient) DeleteReviewPermanent(ctx context.Context, in *FindByIdReviewRequest, opts ...grpc.CallOption) (*ApiResponseReviewDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseReviewDelete)
	err := c.cc.Invoke(ctx, ReviewCommandService_DeleteReviewPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewCommandServiceClient) RestoreAllReview(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseReviewAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseReviewAll)
	err := c.cc.Invoke(ctx, ReviewCommandService_RestoreAllReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewCommandServiceClient) DeleteAllReviewPermanent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseReviewAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseReviewAll)
	err := c.cc.Invoke(ctx, ReviewCommandService_DeleteAllReviewPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewCommandServiceServer is the server API for ReviewCommandService service.
// All implementations must embed UnimplementedReviewCommandServiceServer
// for forward compatibility.
type ReviewCommandServiceServer interface {
	Create(context.Context, *CreateReviewRequest) (*ApiResponseReview, error)
	Update(context.Context, *UpdateReviewRequest) (*ApiResponseReview, error)
	TrashedReview(context.Context, *FindByIdReviewRequest) (*ApiResponseReviewDeleteAt, error)
	RestoreReview(context.Context, *FindByIdReviewRequest) (*ApiResponseReviewDeleteAt, error)
	DeleteReviewPermanent(context.Context, *FindByIdReviewRequest) (*ApiResponseReviewDelete, error)
	RestoreAllReview(context.Context, *emptypb.Empty) (*ApiResponseReviewAll, error)
	DeleteAllReviewPermanent(context.Context, *emptypb.Empty) (*ApiResponseReviewAll, error)
	mustEmbedUnimplementedReviewCommandServiceServer()
}

// UnimplementedReviewCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReviewCommandServiceServer struct{}

func (UnimplementedReviewCommandServiceServer) Create(context.Context, *CreateReviewRequest) (*ApiResponseReview, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedReviewCommandServiceServer) Update(context.Context, *UpdateReviewRequest) (*ApiResponseReview, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedReviewCommandServiceServer) TrashedReview(context.Context, *FindByIdReviewRequest) (*ApiResponseReviewDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method TrashedReview not implemented")
}
func (UnimplementedReviewCommandServiceServer) RestoreReview(context.Context, *FindByIdReviewRequest) (*ApiResponseReviewDeleteAt, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreReview not implemented")
}
func (UnimplementedReviewCommandServiceServer) DeleteReviewPermanent(context.Context, *FindByIdReviewRequest) (*ApiResponseReviewDelete, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteReviewPermanent not implemented")
}
func (UnimplementedReviewCommandServiceServer) RestoreAllReview(context.Context, *emptypb.Empty) (*ApiResponseReviewAll, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreAllReview not implemented")
}
func (UnimplementedReviewCommandServiceServer) DeleteAllReviewPermanent(context.Context, *emptypb.Empty) (*ApiResponseReviewAll, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAllReviewPermanent not implemented")
}
func (UnimplementedReviewCommandServiceServer) mustEmbedUnimplementedReviewCommandServiceServer() {}
func (UnimplementedReviewCommandServiceServer) testEmbeddedByValue()                              {}

// UnsafeReviewCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewCommandServiceServer will
// result in compilation errors.
type UnsafeReviewCommandServiceServer interface {
	mustEmbedUnimplementedReviewCommandServiceServer()
}

func RegisterReviewCommandServiceServer(s grpc.ServiceRegistrar, srv ReviewCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedReviewCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReviewCommandService_ServiceDesc, srv)
}

func _ReviewCommandService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewCommandServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewCommandService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewCommandServiceServer).Create(ctx, req.(*CreateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewCommandService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewCommandServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewCommandService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewCommandServiceServer).Update(ctx, req.(*UpdateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewCommandService_TrashedReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewCommandServiceServer).TrashedReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewCommandService_TrashedReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewCommandServiceServer).TrashedReview(ctx, req.(*FindByIdReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewCommandService_RestoreReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewCommandServiceServer).RestoreReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewCommandService_RestoreReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewCommandServiceServer).RestoreReview(ctx, req.(*FindByIdReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewCommandService_DeleteReviewPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewCommandServiceServer).DeleteReviewPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewCommandService_DeleteReviewPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewCommandServiceServer).DeleteReviewPermanent(ctx, req.(*FindByIdReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewCommandService_RestoreAllReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewCommandServiceServer).RestoreAllReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewCommandService_RestoreAllReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewCommandServiceServer).RestoreAllReview(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewCommandService_DeleteAllReviewPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewCommandServiceServer).DeleteAllReviewPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewCommandService_DeleteAllReviewPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewCommandServiceServer).DeleteAllReviewPermanent(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewCommandService_ServiceDesc is the grpc.ServiceDesc for ReviewCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.review.ReviewCommandService",
	HandlerType: (*ReviewCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ReviewCommandService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ReviewCommandService_Update_Handler,
		},
		{
			MethodName: "TrashedReview",
			Handler:    _ReviewCommandService_TrashedReview_Handler,
		},
		{
			MethodName: "RestoreReview",
			Handler:    _ReviewCommandService_RestoreReview_Handler,
		},
		{
			MethodName: "DeleteReviewPermanent",
			Handler:    _ReviewCommandService_DeleteReviewPermanent_Handler,
		},
		{
			MethodName: "RestoreAllReview",
			Handler:    _ReviewCommandService_RestoreAllReview_Handler,
		},
		{
			MethodName: "DeleteAllReviewPermanent",
			Handler:    _ReviewCommandService_DeleteAllReviewPermanent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review/review_command.proto",
}
