apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- shipping_address-deployment.yaml
- shipping_address-hpa.yaml
- shipping_address-service.yaml
- pdb.yaml
- network-policy.yaml
