// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: cart/cart_query.proto

package monolith_graphql_ecommerce_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllCartRequest) Reset() {
	*x = FindAllCartRequest{}
	mi := &file_cart_cart_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllCartRequest) ProtoMessage() {}

func (x *FindAllCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllCartRequest.ProtoReflect.Descriptor instead.
func (*FindAllCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllCartRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FindAllCartRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllCartRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllCartRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdCartRequest) Reset() {
	*x = FindByIdCartRequest{}
	mi := &file_cart_cart_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdCartRequest) ProtoMessage() {}

func (x *FindByIdCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdCartRequest.ProtoReflect.Descriptor instead.
func (*FindByIdCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindByIdCartRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_cart_cart_query_proto protoreflect.FileDescriptor

const file_cart_cart_query_proto_rawDesc = "" +
	"\n" +
	"\x15cart/cart_query.proto\x12\x02pb\x1a\x16cart/cart_common.proto\"v\n" +
	"\x12FindAllCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"%\n" +
	"\x13FindByIdCartRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2T\n" +
	"\x10CartQueryService\x12@\n" +
	"\aFindAll\x12\x16.pb.FindAllCartRequest\x1a\x1d.pb.ApiResponsePaginationCartB5Z3github.com/MamangRust/monolith-graphql-ecommerce-pbb\x06proto3"

var (
	file_cart_cart_query_proto_rawDescOnce sync.Once
	file_cart_cart_query_proto_rawDescData []byte
)

func file_cart_cart_query_proto_rawDescGZIP() []byte {
	file_cart_cart_query_proto_rawDescOnce.Do(func() {
		file_cart_cart_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_cart_query_proto_rawDesc), len(file_cart_cart_query_proto_rawDesc)))
	})
	return file_cart_cart_query_proto_rawDescData
}

var file_cart_cart_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cart_cart_query_proto_goTypes = []any{
	(*FindAllCartRequest)(nil),        // 0: pb.FindAllCartRequest
	(*FindByIdCartRequest)(nil),       // 1: pb.FindByIdCartRequest
	(*ApiResponsePaginationCart)(nil), // 2: pb.ApiResponsePaginationCart
}
var file_cart_cart_query_proto_depIdxs = []int32{
	0, // 0: pb.CartQueryService.FindAll:input_type -> pb.FindAllCartRequest
	2, // 1: pb.CartQueryService.FindAll:output_type -> pb.ApiResponsePaginationCart
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cart_cart_query_proto_init() }
func file_cart_cart_query_proto_init() {
	if File_cart_cart_query_proto != nil {
		return
	}
	file_cart_cart_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_cart_query_proto_rawDesc), len(file_cart_cart_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_cart_query_proto_goTypes,
		DependencyIndexes: file_cart_cart_query_proto_depIdxs,
		MessageInfos:      file_cart_cart_query_proto_msgTypes,
	}.Build()
	File_cart_cart_query_proto = out.File
	file_cart_cart_query_proto_goTypes = nil
	file_cart_cart_query_proto_depIdxs = nil
}
