// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: merchant_business/merchant_business_command.proto

package monolith_graphql_ecommerce_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMerchantBusinessRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MerchantId        int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	BusinessType      string                 `protobuf:"bytes,2,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	TaxId             string                 `protobuf:"bytes,3,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	EstablishedYear   int32                  `protobuf:"varint,4,opt,name=established_year,json=establishedYear,proto3" json:"established_year,omitempty"`
	NumberOfEmployees int32                  `protobuf:"varint,5,opt,name=number_of_employees,json=numberOfEmployees,proto3" json:"number_of_employees,omitempty"`
	WebsiteUrl        string                 `protobuf:"bytes,6,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateMerchantBusinessRequest) Reset() {
	*x = CreateMerchantBusinessRequest{}
	mi := &file_merchant_business_merchant_business_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantBusinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantBusinessRequest) ProtoMessage() {}

func (x *CreateMerchantBusinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_business_merchant_business_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantBusinessRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantBusinessRequest) Descriptor() ([]byte, []int) {
	return file_merchant_business_merchant_business_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMerchantBusinessRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateMerchantBusinessRequest) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *CreateMerchantBusinessRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *CreateMerchantBusinessRequest) GetEstablishedYear() int32 {
	if x != nil {
		return x.EstablishedYear
	}
	return 0
}

func (x *CreateMerchantBusinessRequest) GetNumberOfEmployees() int32 {
	if x != nil {
		return x.NumberOfEmployees
	}
	return 0
}

func (x *CreateMerchantBusinessRequest) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

type UpdateMerchantBusinessRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MerchantBusinessInfoId int32                  `protobuf:"varint,1,opt,name=merchant_business_info_id,json=merchantBusinessInfoId,proto3" json:"merchant_business_info_id,omitempty"`
	BusinessType           string                 `protobuf:"bytes,2,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	TaxId                  string                 `protobuf:"bytes,3,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	EstablishedYear        int32                  `protobuf:"varint,4,opt,name=established_year,json=establishedYear,proto3" json:"established_year,omitempty"`
	NumberOfEmployees      int32                  `protobuf:"varint,5,opt,name=number_of_employees,json=numberOfEmployees,proto3" json:"number_of_employees,omitempty"`
	WebsiteUrl             string                 `protobuf:"bytes,6,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateMerchantBusinessRequest) Reset() {
	*x = UpdateMerchantBusinessRequest{}
	mi := &file_merchant_business_merchant_business_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantBusinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantBusinessRequest) ProtoMessage() {}

func (x *UpdateMerchantBusinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_business_merchant_business_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantBusinessRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantBusinessRequest) Descriptor() ([]byte, []int) {
	return file_merchant_business_merchant_business_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMerchantBusinessRequest) GetMerchantBusinessInfoId() int32 {
	if x != nil {
		return x.MerchantBusinessInfoId
	}
	return 0
}

func (x *UpdateMerchantBusinessRequest) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *UpdateMerchantBusinessRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *UpdateMerchantBusinessRequest) GetEstablishedYear() int32 {
	if x != nil {
		return x.EstablishedYear
	}
	return 0
}

func (x *UpdateMerchantBusinessRequest) GetNumberOfEmployees() int32 {
	if x != nil {
		return x.NumberOfEmployees
	}
	return 0
}

func (x *UpdateMerchantBusinessRequest) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

var File_merchant_business_merchant_business_command_proto protoreflect.FileDescriptor

const file_merchant_business_merchant_business_command_proto_rawDesc = "" +
	"\n" +
	"1merchant_business/merchant_business_command.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a0merchant_business/merchant_business_common.proto\x1a\x1emerchant/merchant_common.proto\"\xf8\x01\n" +
	"\x1dCreateMerchantBusinessRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12#\n" +
	"\rbusiness_type\x18\x02 \x01(\tR\fbusinessType\x12\x15\n" +
	"\x06tax_id\x18\x03 \x01(\tR\x05taxId\x12)\n" +
	"\x10established_year\x18\x04 \x01(\x05R\x0festablishedYear\x12.\n" +
	"\x13number_of_employees\x18\x05 \x01(\x05R\x11numberOfEmployees\x12\x1f\n" +
	"\vwebsite_url\x18\x06 \x01(\tR\n" +
	"websiteUrl\"\x92\x02\n" +
	"\x1dUpdateMerchantBusinessRequest\x129\n" +
	"\x19merchant_business_info_id\x18\x01 \x01(\x05R\x16merchantBusinessInfoId\x12#\n" +
	"\rbusiness_type\x18\x02 \x01(\tR\fbusinessType\x12\x15\n" +
	"\x06tax_id\x18\x03 \x01(\tR\x05taxId\x12)\n" +
	"\x10established_year\x18\x04 \x01(\x05R\x0festablishedYear\x12.\n" +
	"\x13number_of_employees\x18\x05 \x01(\x05R\x11numberOfEmployees\x12\x1f\n" +
	"\vwebsite_url\x18\x06 \x01(\tR\n" +
	"websiteUrl2\xa1\x05\n" +
	"\x1eMerchantBusinessCommandService\x12L\n" +
	"\x06Create\x12!.pb.CreateMerchantBusinessRequest\x1a\x1f.pb.ApiResponseMerchantBusiness\x12L\n" +
	"\x06Update\x12!.pb.UpdateMerchantBusinessRequest\x1a\x1f.pb.ApiResponseMerchantBusiness\x12g\n" +
	"\x17TrashedMerchantBusiness\x12#.pb.FindByIdMerchantBusinessRequest\x1a'.pb.ApiResponseMerchantBusinessDeleteAt\x12g\n" +
	"\x17RestoreMerchantBusiness\x12#.pb.FindByIdMerchantBusinessRequest\x1a'.pb.ApiResponseMerchantBusinessDeleteAt\x12e\n" +
	"\x1fDeleteMerchantBusinessPermanent\x12#.pb.FindByIdMerchantBusinessRequest\x1a\x1d.pb.ApiResponseMerchantDelete\x12P\n" +
	"\x1aRestoreAllMerchantBusiness\x12\x16.google.protobuf.Empty\x1a\x1a.pb.ApiResponseMerchantAll\x12X\n" +
	"\"DeleteAllMerchantBusinessPermanent\x12\x16.google.protobuf.Empty\x1a\x1a.pb.ApiResponseMerchantAllB5Z3github.com/MamangRust/monolith-graphql-ecommerce-pbb\x06proto3"

var (
	file_merchant_business_merchant_business_command_proto_rawDescOnce sync.Once
	file_merchant_business_merchant_business_command_proto_rawDescData []byte
)

func file_merchant_business_merchant_business_command_proto_rawDescGZIP() []byte {
	file_merchant_business_merchant_business_command_proto_rawDescOnce.Do(func() {
		file_merchant_business_merchant_business_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_business_merchant_business_command_proto_rawDesc), len(file_merchant_business_merchant_business_command_proto_rawDesc)))
	})
	return file_merchant_business_merchant_business_command_proto_rawDescData
}

var file_merchant_business_merchant_business_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_merchant_business_merchant_business_command_proto_goTypes = []any{
	(*CreateMerchantBusinessRequest)(nil),       // 0: pb.CreateMerchantBusinessRequest
	(*UpdateMerchantBusinessRequest)(nil),       // 1: pb.UpdateMerchantBusinessRequest
	(*FindByIdMerchantBusinessRequest)(nil),     // 2: pb.FindByIdMerchantBusinessRequest
	(*emptypb.Empty)(nil),                       // 3: google.protobuf.Empty
	(*ApiResponseMerchantBusiness)(nil),         // 4: pb.ApiResponseMerchantBusiness
	(*ApiResponseMerchantBusinessDeleteAt)(nil), // 5: pb.ApiResponseMerchantBusinessDeleteAt
	(*ApiResponseMerchantDelete)(nil),           // 6: pb.ApiResponseMerchantDelete
	(*ApiResponseMerchantAll)(nil),              // 7: pb.ApiResponseMerchantAll
}
var file_merchant_business_merchant_business_command_proto_depIdxs = []int32{
	0, // 0: pb.MerchantBusinessCommandService.Create:input_type -> pb.CreateMerchantBusinessRequest
	1, // 1: pb.MerchantBusinessCommandService.Update:input_type -> pb.UpdateMerchantBusinessRequest
	2, // 2: pb.MerchantBusinessCommandService.TrashedMerchantBusiness:input_type -> pb.FindByIdMerchantBusinessRequest
	2, // 3: pb.MerchantBusinessCommandService.RestoreMerchantBusiness:input_type -> pb.FindByIdMerchantBusinessRequest
	2, // 4: pb.MerchantBusinessCommandService.DeleteMerchantBusinessPermanent:input_type -> pb.FindByIdMerchantBusinessRequest
	3, // 5: pb.MerchantBusinessCommandService.RestoreAllMerchantBusiness:input_type -> google.protobuf.Empty
	3, // 6: pb.MerchantBusinessCommandService.DeleteAllMerchantBusinessPermanent:input_type -> google.protobuf.Empty
	4, // 7: pb.MerchantBusinessCommandService.Create:output_type -> pb.ApiResponseMerchantBusiness
	4, // 8: pb.MerchantBusinessCommandService.Update:output_type -> pb.ApiResponseMerchantBusiness
	5, // 9: pb.MerchantBusinessCommandService.TrashedMerchantBusiness:output_type -> pb.ApiResponseMerchantBusinessDeleteAt
	5, // 10: pb.MerchantBusinessCommandService.RestoreMerchantBusiness:output_type -> pb.ApiResponseMerchantBusinessDeleteAt
	6, // 11: pb.MerchantBusinessCommandService.DeleteMerchantBusinessPermanent:output_type -> pb.ApiResponseMerchantDelete
	7, // 12: pb.MerchantBusinessCommandService.RestoreAllMerchantBusiness:output_type -> pb.ApiResponseMerchantAll
	7, // 13: pb.MerchantBusinessCommandService.DeleteAllMerchantBusinessPermanent:output_type -> pb.ApiResponseMerchantAll
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_merchant_business_merchant_business_command_proto_init() }
func file_merchant_business_merchant_business_command_proto_init() {
	if File_merchant_business_merchant_business_command_proto != nil {
		return
	}
	file_merchant_business_merchant_business_common_proto_init()
	file_merchant_merchant_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_business_merchant_business_command_proto_rawDesc), len(file_merchant_business_merchant_business_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_business_merchant_business_command_proto_goTypes,
		DependencyIndexes: file_merchant_business_merchant_business_command_proto_depIdxs,
		MessageInfos:      file_merchant_business_merchant_business_command_proto_msgTypes,
	}.Build()
	File_merchant_business_merchant_business_command_proto = out.File
	file_merchant_business_merchant_business_command_proto_goTypes = nil
	file_merchant_business_merchant_business_command_proto_depIdxs = nil
}
