// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: merchant_social_link/merchant_social_link_command.proto

package monolith_graphql_ecommerce_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantSocialLinkService_CreateMerchantSocialLink_FullMethodName = "/pb.MerchantSocialLinkService/CreateMerchantSocialLink"
	MerchantSocialLinkService_UpdateMerchantSocialLink_FullMethodName = "/pb.MerchantSocialLinkService/UpdateMerchantSocialLink"
)

// MerchantSocialLinkServiceClient is the client API for MerchantSocialLinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantSocialLinkServiceClient interface {
	CreateMerchantSocialLink(ctx context.Context, in *CreateMerchantSocialInput, opts ...grpc.CallOption) (*ApiResponseMerchantSocialMediaLink, error)
	UpdateMerchantSocialLink(ctx context.Context, in *UpdateMerchantSocialInput, opts ...grpc.CallOption) (*ApiResponseMerchantSocialMediaLink, error)
}

type merchantSocialLinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantSocialLinkServiceClient(cc grpc.ClientConnInterface) MerchantSocialLinkServiceClient {
	return &merchantSocialLinkServiceClient{cc}
}

func (c *merchantSocialLinkServiceClient) CreateMerchantSocialLink(ctx context.Context, in *CreateMerchantSocialInput, opts ...grpc.CallOption) (*ApiResponseMerchantSocialMediaLink, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantSocialMediaLink)
	err := c.cc.Invoke(ctx, MerchantSocialLinkService_CreateMerchantSocialLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantSocialLinkServiceClient) UpdateMerchantSocialLink(ctx context.Context, in *UpdateMerchantSocialInput, opts ...grpc.CallOption) (*ApiResponseMerchantSocialMediaLink, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantSocialMediaLink)
	err := c.cc.Invoke(ctx, MerchantSocialLinkService_UpdateMerchantSocialLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantSocialLinkServiceServer is the server API for MerchantSocialLinkService service.
// All implementations must embed UnimplementedMerchantSocialLinkServiceServer
// for forward compatibility.
type MerchantSocialLinkServiceServer interface {
	CreateMerchantSocialLink(context.Context, *CreateMerchantSocialInput) (*ApiResponseMerchantSocialMediaLink, error)
	UpdateMerchantSocialLink(context.Context, *UpdateMerchantSocialInput) (*ApiResponseMerchantSocialMediaLink, error)
	mustEmbedUnimplementedMerchantSocialLinkServiceServer()
}

// UnimplementedMerchantSocialLinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantSocialLinkServiceServer struct{}

func (UnimplementedMerchantSocialLinkServiceServer) CreateMerchantSocialLink(context.Context, *CreateMerchantSocialInput) (*ApiResponseMerchantSocialMediaLink, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMerchantSocialLink not implemented")
}
func (UnimplementedMerchantSocialLinkServiceServer) UpdateMerchantSocialLink(context.Context, *UpdateMerchantSocialInput) (*ApiResponseMerchantSocialMediaLink, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMerchantSocialLink not implemented")
}
func (UnimplementedMerchantSocialLinkServiceServer) mustEmbedUnimplementedMerchantSocialLinkServiceServer() {
}
func (UnimplementedMerchantSocialLinkServiceServer) testEmbeddedByValue() {}

// UnsafeMerchantSocialLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantSocialLinkServiceServer will
// result in compilation errors.
type UnsafeMerchantSocialLinkServiceServer interface {
	mustEmbedUnimplementedMerchantSocialLinkServiceServer()
}

func RegisterMerchantSocialLinkServiceServer(s grpc.ServiceRegistrar, srv MerchantSocialLinkServiceServer) {
	// If the following call pancis, it indicates UnimplementedMerchantSocialLinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantSocialLinkService_ServiceDesc, srv)
}

func _MerchantSocialLinkService_CreateMerchantSocialLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMerchantSocialInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantSocialLinkServiceServer).CreateMerchantSocialLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantSocialLinkService_CreateMerchantSocialLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantSocialLinkServiceServer).CreateMerchantSocialLink(ctx, req.(*CreateMerchantSocialInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantSocialLinkService_UpdateMerchantSocialLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMerchantSocialInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantSocialLinkServiceServer).UpdateMerchantSocialLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantSocialLinkService_UpdateMerchantSocialLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantSocialLinkServiceServer).UpdateMerchantSocialLink(ctx, req.(*UpdateMerchantSocialInput))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantSocialLinkService_ServiceDesc is the grpc.ServiceDesc for MerchantSocialLinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantSocialLinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MerchantSocialLinkService",
	HandlerType: (*MerchantSocialLinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMerchantSocialLink",
			Handler:    _MerchantSocialLinkService_CreateMerchantSocialLink_Handler,
		},
		{
			MethodName: "UpdateMerchantSocialLink",
			Handler:    _MerchantSocialLinkService_UpdateMerchantSocialLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant_social_link/merchant_social_link_command.proto",
}
