// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: merchant_social_link/merchant_social_link_command.proto

package monolith_graphql_ecommerce_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantSocialLinkInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantSocialLinkInput) Reset() {
	*x = MerchantSocialLinkInput{}
	mi := &file_merchant_social_link_merchant_social_link_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantSocialLinkInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantSocialLinkInput) ProtoMessage() {}

func (x *MerchantSocialLinkInput) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_social_link_merchant_social_link_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantSocialLinkInput.ProtoReflect.Descriptor instead.
func (*MerchantSocialLinkInput) Descriptor() ([]byte, []int) {
	return file_merchant_social_link_merchant_social_link_command_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantSocialLinkInput) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *MerchantSocialLinkInput) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateMerchantSocialInput struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	MerchantDetailId int32                      `protobuf:"varint,1,opt,name=merchant_detail_id,json=merchantDetailId,proto3" json:"merchant_detail_id,omitempty"`
	SocialLinks      []*MerchantSocialLinkInput `protobuf:"bytes,2,rep,name=social_links,json=socialLinks,proto3" json:"social_links,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateMerchantSocialInput) Reset() {
	*x = CreateMerchantSocialInput{}
	mi := &file_merchant_social_link_merchant_social_link_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantSocialInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantSocialInput) ProtoMessage() {}

func (x *CreateMerchantSocialInput) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_social_link_merchant_social_link_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantSocialInput.ProtoReflect.Descriptor instead.
func (*CreateMerchantSocialInput) Descriptor() ([]byte, []int) {
	return file_merchant_social_link_merchant_social_link_command_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMerchantSocialInput) GetMerchantDetailId() int32 {
	if x != nil {
		return x.MerchantDetailId
	}
	return 0
}

func (x *CreateMerchantSocialInput) GetSocialLinks() []*MerchantSocialLinkInput {
	if x != nil {
		return x.SocialLinks
	}
	return nil
}

type UpdateMerchantSocialInput struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	MerchantDetailId int32                      `protobuf:"varint,1,opt,name=merchant_detail_id,json=merchantDetailId,proto3" json:"merchant_detail_id,omitempty"`
	SocialLinks      []*MerchantSocialLinkInput `protobuf:"bytes,2,rep,name=social_links,json=socialLinks,proto3" json:"social_links,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateMerchantSocialInput) Reset() {
	*x = UpdateMerchantSocialInput{}
	mi := &file_merchant_social_link_merchant_social_link_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantSocialInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantSocialInput) ProtoMessage() {}

func (x *UpdateMerchantSocialInput) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_social_link_merchant_social_link_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantSocialInput.ProtoReflect.Descriptor instead.
func (*UpdateMerchantSocialInput) Descriptor() ([]byte, []int) {
	return file_merchant_social_link_merchant_social_link_command_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMerchantSocialInput) GetMerchantDetailId() int32 {
	if x != nil {
		return x.MerchantDetailId
	}
	return 0
}

func (x *UpdateMerchantSocialInput) GetSocialLinks() []*MerchantSocialLinkInput {
	if x != nil {
		return x.SocialLinks
	}
	return nil
}

type ApiResponseMerchantSocialMediaLink struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Status        string                             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantSocialMediaLinkResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantSocialMediaLink) Reset() {
	*x = ApiResponseMerchantSocialMediaLink{}
	mi := &file_merchant_social_link_merchant_social_link_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantSocialMediaLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantSocialMediaLink) ProtoMessage() {}

func (x *ApiResponseMerchantSocialMediaLink) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_social_link_merchant_social_link_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantSocialMediaLink.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantSocialMediaLink) Descriptor() ([]byte, []int) {
	return file_merchant_social_link_merchant_social_link_command_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseMerchantSocialMediaLink) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantSocialMediaLink) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantSocialMediaLink) GetData() []*MerchantSocialMediaLinkResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_merchant_social_link_merchant_social_link_command_proto protoreflect.FileDescriptor

const file_merchant_social_link_merchant_social_link_command_proto_rawDesc = "" +
	"\n" +
	"7merchant_social_link/merchant_social_link_command.proto\x12\x02pb\x1a,merchant_detail/merchant_detail_common.proto\"G\n" +
	"\x17MerchantSocialLinkInput\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x89\x01\n" +
	"\x19CreateMerchantSocialInput\x12,\n" +
	"\x12merchant_detail_id\x18\x01 \x01(\x05R\x10merchantDetailId\x12>\n" +
	"\fsocial_links\x18\x02 \x03(\v2\x1b.pb.MerchantSocialLinkInputR\vsocialLinks\"\x89\x01\n" +
	"\x19UpdateMerchantSocialInput\x12,\n" +
	"\x12merchant_detail_id\x18\x01 \x01(\x05R\x10merchantDetailId\x12>\n" +
	"\fsocial_links\x18\x02 \x03(\v2\x1b.pb.MerchantSocialLinkInputR\vsocialLinks\"\x8f\x01\n" +
	"\"ApiResponseMerchantSocialMediaLink\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.pb.MerchantSocialMediaLinkResponseR\x04data2\xe1\x01\n" +
	"\x19MerchantSocialLinkService\x12a\n" +
	"\x18CreateMerchantSocialLink\x12\x1d.pb.CreateMerchantSocialInput\x1a&.pb.ApiResponseMerchantSocialMediaLink\x12a\n" +
	"\x18UpdateMerchantSocialLink\x12\x1d.pb.UpdateMerchantSocialInput\x1a&.pb.ApiResponseMerchantSocialMediaLinkB5Z3github.com/MamangRust/monolith-graphql-ecommerce-pbb\x06proto3"

var (
	file_merchant_social_link_merchant_social_link_command_proto_rawDescOnce sync.Once
	file_merchant_social_link_merchant_social_link_command_proto_rawDescData []byte
)

func file_merchant_social_link_merchant_social_link_command_proto_rawDescGZIP() []byte {
	file_merchant_social_link_merchant_social_link_command_proto_rawDescOnce.Do(func() {
		file_merchant_social_link_merchant_social_link_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_social_link_merchant_social_link_command_proto_rawDesc), len(file_merchant_social_link_merchant_social_link_command_proto_rawDesc)))
	})
	return file_merchant_social_link_merchant_social_link_command_proto_rawDescData
}

var file_merchant_social_link_merchant_social_link_command_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_merchant_social_link_merchant_social_link_command_proto_goTypes = []any{
	(*MerchantSocialLinkInput)(nil),            // 0: pb.MerchantSocialLinkInput
	(*CreateMerchantSocialInput)(nil),          // 1: pb.CreateMerchantSocialInput
	(*UpdateMerchantSocialInput)(nil),          // 2: pb.UpdateMerchantSocialInput
	(*ApiResponseMerchantSocialMediaLink)(nil), // 3: pb.ApiResponseMerchantSocialMediaLink
	(*MerchantSocialMediaLinkResponse)(nil),    // 4: pb.MerchantSocialMediaLinkResponse
}
var file_merchant_social_link_merchant_social_link_command_proto_depIdxs = []int32{
	0, // 0: pb.CreateMerchantSocialInput.social_links:type_name -> pb.MerchantSocialLinkInput
	0, // 1: pb.UpdateMerchantSocialInput.social_links:type_name -> pb.MerchantSocialLinkInput
	4, // 2: pb.ApiResponseMerchantSocialMediaLink.data:type_name -> pb.MerchantSocialMediaLinkResponse
	1, // 3: pb.MerchantSocialLinkService.CreateMerchantSocialLink:input_type -> pb.CreateMerchantSocialInput
	2, // 4: pb.MerchantSocialLinkService.UpdateMerchantSocialLink:input_type -> pb.UpdateMerchantSocialInput
	3, // 5: pb.MerchantSocialLinkService.CreateMerchantSocialLink:output_type -> pb.ApiResponseMerchantSocialMediaLink
	3, // 6: pb.MerchantSocialLinkService.UpdateMerchantSocialLink:output_type -> pb.ApiResponseMerchantSocialMediaLink
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_merchant_social_link_merchant_social_link_command_proto_init() }
func file_merchant_social_link_merchant_social_link_command_proto_init() {
	if File_merchant_social_link_merchant_social_link_command_proto != nil {
		return
	}
	file_merchant_detail_merchant_detail_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_social_link_merchant_social_link_command_proto_rawDesc), len(file_merchant_social_link_merchant_social_link_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_social_link_merchant_social_link_command_proto_goTypes,
		DependencyIndexes: file_merchant_social_link_merchant_social_link_command_proto_depIdxs,
		MessageInfos:      file_merchant_social_link_merchant_social_link_command_proto_msgTypes,
	}.Build()
	File_merchant_social_link_merchant_social_link_command_proto = out.File
	file_merchant_social_link_merchant_social_link_command_proto_goTypes = nil
	file_merchant_social_link_merchant_social_link_command_proto_depIdxs = nil
}
