// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: merchant_detail/merchant_detail_query.proto

package monolith_graphql_ecommerce_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllMerchantDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllMerchantDetailRequest) Reset() {
	*x = FindAllMerchantDetailRequest{}
	mi := &file_merchant_detail_merchant_detail_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllMerchantDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllMerchantDetailRequest) ProtoMessage() {}

func (x *FindAllMerchantDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_merchant_detail_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllMerchantDetailRequest.ProtoReflect.Descriptor instead.
func (*FindAllMerchantDetailRequest) Descriptor() ([]byte, []int) {
	return file_merchant_detail_merchant_detail_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllMerchantDetailRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllMerchantDetailRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllMerchantDetailRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

var File_merchant_detail_merchant_detail_query_proto protoreflect.FileDescriptor

const file_merchant_detail_merchant_detail_query_proto_rawDesc = "" +
	"\n" +
	"+merchant_detail/merchant_detail_query.proto\x12\x02pb\x1a,merchant_detail/merchant_detail_common.proto\x1a\x1dmerchant/merchant_query.proto\"g\n" +
	"\x1cFindAllMerchantDetailRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search2\xf5\x02\n" +
	"\x1aMerchantDetailQueryService\x12N\n" +
	"\aFindAll\x12\x1a.pb.FindAllMerchantRequest\x1a'.pb.ApiResponsePaginationMerchantDetail\x12L\n" +
	"\bFindById\x12!.pb.FindByIdMerchantDetailRequest\x1a\x1d.pb.ApiResponseMerchantDetail\x12[\n" +
	"\fFindByActive\x12\x1a.pb.FindAllMerchantRequest\x1a/.pb.ApiResponsePaginationMerchantDetailDeleteAt\x12\\\n" +
	"\rFindByTrashed\x12\x1a.pb.FindAllMerchantRequest\x1a/.pb.ApiResponsePaginationMerchantDetailDeleteAtB5Z3github.com/MamangRust/monolith-graphql-ecommerce-pbb\x06proto3"

var (
	file_merchant_detail_merchant_detail_query_proto_rawDescOnce sync.Once
	file_merchant_detail_merchant_detail_query_proto_rawDescData []byte
)

func file_merchant_detail_merchant_detail_query_proto_rawDescGZIP() []byte {
	file_merchant_detail_merchant_detail_query_proto_rawDescOnce.Do(func() {
		file_merchant_detail_merchant_detail_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_detail_merchant_detail_query_proto_rawDesc), len(file_merchant_detail_merchant_detail_query_proto_rawDesc)))
	})
	return file_merchant_detail_merchant_detail_query_proto_rawDescData
}

var file_merchant_detail_merchant_detail_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_merchant_detail_merchant_detail_query_proto_goTypes = []any{
	(*FindAllMerchantDetailRequest)(nil),                // 0: pb.FindAllMerchantDetailRequest
	(*FindAllMerchantRequest)(nil),                      // 1: pb.FindAllMerchantRequest
	(*FindByIdMerchantDetailRequest)(nil),               // 2: pb.FindByIdMerchantDetailRequest
	(*ApiResponsePaginationMerchantDetail)(nil),         // 3: pb.ApiResponsePaginationMerchantDetail
	(*ApiResponseMerchantDetail)(nil),                   // 4: pb.ApiResponseMerchantDetail
	(*ApiResponsePaginationMerchantDetailDeleteAt)(nil), // 5: pb.ApiResponsePaginationMerchantDetailDeleteAt
}
var file_merchant_detail_merchant_detail_query_proto_depIdxs = []int32{
	1, // 0: pb.MerchantDetailQueryService.FindAll:input_type -> pb.FindAllMerchantRequest
	2, // 1: pb.MerchantDetailQueryService.FindById:input_type -> pb.FindByIdMerchantDetailRequest
	1, // 2: pb.MerchantDetailQueryService.FindByActive:input_type -> pb.FindAllMerchantRequest
	1, // 3: pb.MerchantDetailQueryService.FindByTrashed:input_type -> pb.FindAllMerchantRequest
	3, // 4: pb.MerchantDetailQueryService.FindAll:output_type -> pb.ApiResponsePaginationMerchantDetail
	4, // 5: pb.MerchantDetailQueryService.FindById:output_type -> pb.ApiResponseMerchantDetail
	5, // 6: pb.MerchantDetailQueryService.FindByActive:output_type -> pb.ApiResponsePaginationMerchantDetailDeleteAt
	5, // 7: pb.MerchantDetailQueryService.FindByTrashed:output_type -> pb.ApiResponsePaginationMerchantDetailDeleteAt
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_merchant_detail_merchant_detail_query_proto_init() }
func file_merchant_detail_merchant_detail_query_proto_init() {
	if File_merchant_detail_merchant_detail_query_proto != nil {
		return
	}
	file_merchant_detail_merchant_detail_common_proto_init()
	file_merchant_merchant_query_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_detail_merchant_detail_query_proto_rawDesc), len(file_merchant_detail_merchant_detail_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_detail_merchant_detail_query_proto_goTypes,
		DependencyIndexes: file_merchant_detail_merchant_detail_query_proto_depIdxs,
		MessageInfos:      file_merchant_detail_merchant_detail_query_proto_msgTypes,
	}.Build()
	File_merchant_detail_merchant_detail_query_proto = out.File
	file_merchant_detail_merchant_detail_query_proto_goTypes = nil
	file_merchant_detail_merchant_detail_query_proto_depIdxs = nil
}
