// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: merchant_award/merchant_award_command.proto

package monolith_graphql_ecommerce_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantAwardCommandService_Create_FullMethodName                          = "/pb.MerchantAwardCommandService/Create"
	MerchantAwardCommandService_Update_FullMethodName                          = "/pb.MerchantAwardCommandService/Update"
	MerchantAwardCommandService_TrashedMerchantAward_FullMethodName            = "/pb.MerchantAwardCommandService/TrashedMerchantAward"
	MerchantAwardCommandService_RestoreMerchantAward_FullMethodName            = "/pb.MerchantAwardCommandService/RestoreMerchantAward"
	MerchantAwardCommandService_DeleteMerchantAwardPermanent_FullMethodName    = "/pb.MerchantAwardCommandService/DeleteMerchantAwardPermanent"
	MerchantAwardCommandService_RestoreAllMerchantAward_FullMethodName         = "/pb.MerchantAwardCommandService/RestoreAllMerchantAward"
	MerchantAwardCommandService_DeleteAllMerchantAwardPermanent_FullMethodName = "/pb.MerchantAwardCommandService/DeleteAllMerchantAwardPermanent"
)

// MerchantAwardCommandServiceClient is the client API for MerchantAwardCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantAwardCommandServiceClient interface {
	Create(ctx context.Context, in *CreateMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantAward, error)
	Update(ctx context.Context, in *UpdateMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantAward, error)
	TrashedMerchantAward(ctx context.Context, in *FindByIdMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantAwardDeleteAt, error)
	RestoreMerchantAward(ctx context.Context, in *FindByIdMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantAwardDeleteAt, error)
	DeleteMerchantAwardPermanent(ctx context.Context, in *FindByIdMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantDelete, error)
	RestoreAllMerchantAward(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseMerchantAll, error)
	DeleteAllMerchantAwardPermanent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseMerchantAll, error)
}

type merchantAwardCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantAwardCommandServiceClient(cc grpc.ClientConnInterface) MerchantAwardCommandServiceClient {
	return &merchantAwardCommandServiceClient{cc}
}

func (c *merchantAwardCommandServiceClient) Create(ctx context.Context, in *CreateMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantAward, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantAward)
	err := c.cc.Invoke(ctx, MerchantAwardCommandService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantAwardCommandServiceClient) Update(ctx context.Context, in *UpdateMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantAward, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantAward)
	err := c.cc.Invoke(ctx, MerchantAwardCommandService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantAwardCommandServiceClient) TrashedMerchantAward(ctx context.Context, in *FindByIdMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantAwardDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantAwardDeleteAt)
	err := c.cc.Invoke(ctx, MerchantAwardCommandService_TrashedMerchantAward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantAwardCommandServiceClient) RestoreMerchantAward(ctx context.Context, in *FindByIdMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantAwardDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantAwardDeleteAt)
	err := c.cc.Invoke(ctx, MerchantAwardCommandService_RestoreMerchantAward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantAwardCommandServiceClient) DeleteMerchantAwardPermanent(ctx context.Context, in *FindByIdMerchantAwardRequest, opts ...grpc.CallOption) (*ApiResponseMerchantDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantDelete)
	err := c.cc.Invoke(ctx, MerchantAwardCommandService_DeleteMerchantAwardPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantAwardCommandServiceClient) RestoreAllMerchantAward(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseMerchantAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantAll)
	err := c.cc.Invoke(ctx, MerchantAwardCommandService_RestoreAllMerchantAward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantAwardCommandServiceClient) DeleteAllMerchantAwardPermanent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseMerchantAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantAll)
	err := c.cc.Invoke(ctx, MerchantAwardCommandService_DeleteAllMerchantAwardPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantAwardCommandServiceServer is the server API for MerchantAwardCommandService service.
// All implementations must embed UnimplementedMerchantAwardCommandServiceServer
// for forward compatibility.
type MerchantAwardCommandServiceServer interface {
	Create(context.Context, *CreateMerchantAwardRequest) (*ApiResponseMerchantAward, error)
	Update(context.Context, *UpdateMerchantAwardRequest) (*ApiResponseMerchantAward, error)
	TrashedMerchantAward(context.Context, *FindByIdMerchantAwardRequest) (*ApiResponseMerchantAwardDeleteAt, error)
	RestoreMerchantAward(context.Context, *FindByIdMerchantAwardRequest) (*ApiResponseMerchantAwardDeleteAt, error)
	DeleteMerchantAwardPermanent(context.Context, *FindByIdMerchantAwardRequest) (*ApiResponseMerchantDelete, error)
	RestoreAllMerchantAward(context.Context, *emptypb.Empty) (*ApiResponseMerchantAll, error)
	DeleteAllMerchantAwardPermanent(context.Context, *emptypb.Empty) (*ApiResponseMerchantAll, error)
	mustEmbedUnimplementedMerchantAwardCommandServiceServer()
}

// UnimplementedMerchantAwardCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantAwardCommandServiceServer struct{}

func (UnimplementedMerchantAwardCommandServiceServer) Create(context.Context, *CreateMerchantAwardRequest) (*ApiResponseMerchantAward, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedMerchantAwardCommandServiceServer) Update(context.Context, *UpdateMerchantAwardRequest) (*ApiResponseMerchantAward, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedMerchantAwardCommandServiceServer) TrashedMerchantAward(context.Context, *FindByIdMerchantAwardRequest) (*ApiResponseMerchantAwardDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrashedMerchantAward not implemented")
}
func (UnimplementedMerchantAwardCommandServiceServer) RestoreMerchantAward(context.Context, *FindByIdMerchantAwardRequest) (*ApiResponseMerchantAwardDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreMerchantAward not implemented")
}
func (UnimplementedMerchantAwardCommandServiceServer) DeleteMerchantAwardPermanent(context.Context, *FindByIdMerchantAwardRequest) (*ApiResponseMerchantDelete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMerchantAwardPermanent not implemented")
}
func (UnimplementedMerchantAwardCommandServiceServer) RestoreAllMerchantAward(context.Context, *emptypb.Empty) (*ApiResponseMerchantAll, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreAllMerchantAward not implemented")
}
func (UnimplementedMerchantAwardCommandServiceServer) DeleteAllMerchantAwardPermanent(context.Context, *emptypb.Empty) (*ApiResponseMerchantAll, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAllMerchantAwardPermanent not implemented")
}
func (UnimplementedMerchantAwardCommandServiceServer) mustEmbedUnimplementedMerchantAwardCommandServiceServer() {
}
func (UnimplementedMerchantAwardCommandServiceServer) testEmbeddedByValue() {}

// UnsafeMerchantAwardCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantAwardCommandServiceServer will
// result in compilation errors.
type UnsafeMerchantAwardCommandServiceServer interface {
	mustEmbedUnimplementedMerchantAwardCommandServiceServer()
}

func RegisterMerchantAwardCommandServiceServer(s grpc.ServiceRegistrar, srv MerchantAwardCommandServiceServer) {
	// If the following call pancis, it indicates UnimplementedMerchantAwardCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantAwardCommandService_ServiceDesc, srv)
}

func _MerchantAwardCommandService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMerchantAwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAwardCommandServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAwardCommandService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAwardCommandServiceServer).Create(ctx, req.(*CreateMerchantAwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantAwardCommandService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMerchantAwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAwardCommandServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAwardCommandService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAwardCommandServiceServer).Update(ctx, req.(*UpdateMerchantAwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantAwardCommandService_TrashedMerchantAward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdMerchantAwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAwardCommandServiceServer).TrashedMerchantAward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAwardCommandService_TrashedMerchantAward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAwardCommandServiceServer).TrashedMerchantAward(ctx, req.(*FindByIdMerchantAwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantAwardCommandService_RestoreMerchantAward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdMerchantAwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAwardCommandServiceServer).RestoreMerchantAward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAwardCommandService_RestoreMerchantAward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAwardCommandServiceServer).RestoreMerchantAward(ctx, req.(*FindByIdMerchantAwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantAwardCommandService_DeleteMerchantAwardPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdMerchantAwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAwardCommandServiceServer).DeleteMerchantAwardPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAwardCommandService_DeleteMerchantAwardPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAwardCommandServiceServer).DeleteMerchantAwardPermanent(ctx, req.(*FindByIdMerchantAwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantAwardCommandService_RestoreAllMerchantAward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAwardCommandServiceServer).RestoreAllMerchantAward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAwardCommandService_RestoreAllMerchantAward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAwardCommandServiceServer).RestoreAllMerchantAward(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantAwardCommandService_DeleteAllMerchantAwardPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAwardCommandServiceServer).DeleteAllMerchantAwardPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAwardCommandService_DeleteAllMerchantAwardPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAwardCommandServiceServer).DeleteAllMerchantAwardPermanent(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantAwardCommandService_ServiceDesc is the grpc.ServiceDesc for MerchantAwardCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantAwardCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MerchantAwardCommandService",
	HandlerType: (*MerchantAwardCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _MerchantAwardCommandService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MerchantAwardCommandService_Update_Handler,
		},
		{
			MethodName: "TrashedMerchantAward",
			Handler:    _MerchantAwardCommandService_TrashedMerchantAward_Handler,
		},
		{
			MethodName: "RestoreMerchantAward",
			Handler:    _MerchantAwardCommandService_RestoreMerchantAward_Handler,
		},
		{
			MethodName: "DeleteMerchantAwardPermanent",
			Handler:    _MerchantAwardCommandService_DeleteMerchantAwardPermanent_Handler,
		},
		{
			MethodName: "RestoreAllMerchantAward",
			Handler:    _MerchantAwardCommandService_RestoreAllMerchantAward_Handler,
		},
		{
			MethodName: "DeleteAllMerchantAwardPermanent",
			Handler:    _MerchantAwardCommandService_DeleteAllMerchantAwardPermanent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant_award/merchant_award_command.proto",
}
