// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: transaction/transaction_query.proto

package monolith_graphql_ecommerce_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTransactionRequest) Reset() {
	*x = FindAllTransactionRequest{}
	mi := &file_transaction_transaction_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTransactionRequest) ProtoMessage() {}

func (x *FindAllTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTransactionRequest.ProtoReflect.Descriptor instead.
func (*FindAllTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllTransactionRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllTransactionRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllTransactionRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllTransactionByMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTransactionByMerchantRequest) Reset() {
	*x = FindAllTransactionByMerchantRequest{}
	mi := &file_transaction_transaction_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTransactionByMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTransactionByMerchantRequest) ProtoMessage() {}

func (x *FindAllTransactionByMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTransactionByMerchantRequest.ProtoReflect.Descriptor instead.
func (*FindAllTransactionByMerchantRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllTransactionByMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindAllTransactionByMerchantRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllTransactionByMerchantRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllTransactionByMerchantRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByOrderIdTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByOrderIdTransactionRequest) Reset() {
	*x = FindByOrderIdTransactionRequest{}
	mi := &file_transaction_transaction_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByOrderIdTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByOrderIdTransactionRequest) ProtoMessage() {}

func (x *FindByOrderIdTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByOrderIdTransactionRequest.ProtoReflect.Descriptor instead.
func (*FindByOrderIdTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_query_proto_rawDescGZIP(), []int{2}
}

func (x *FindByOrderIdTransactionRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

var File_transaction_transaction_query_proto protoreflect.FileDescriptor

const file_transaction_transaction_query_proto_rawDesc = "" +
	"\n" +
	"#transaction/transaction_query.proto\x12\x02pb\x1a$transaction/transaction_common.proto\"d\n" +
	"\x19FindAllTransactionRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x8f\x01\n" +
	"#FindAllTransactionByMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"<\n" +
	"\x1fFindByOrderIdTransactionRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId2\xab\x04\n" +
	"\x17TransactionQueryService\x12Z\n" +
	"\x13FindAllTransactions\x12\x1d.pb.FindAllTransactionRequest\x1a$.pb.ApiResponsePaginationTransaction\x12_\n" +
	"\x0eFindByMerchant\x12'.pb.FindAllTransactionByMerchantRequest\x1a$.pb.ApiResponsePaginationTransaction\x12F\n" +
	"\bFindById\x12\x1e.pb.FindByIdTransactionRequest\x1a\x1a.pb.ApiResponseTransaction\x12P\n" +
	"\rFindByOrderId\x12#.pb.FindByOrderIdTransactionRequest\x1a\x1a.pb.ApiResponseTransaction\x12[\n" +
	"\fFindByActive\x12\x1d.pb.FindAllTransactionRequest\x1a,.pb.ApiResponsePaginationTransactionDeleteAt\x12\\\n" +
	"\rFindByTrashed\x12\x1d.pb.FindAllTransactionRequest\x1a,.pb.ApiResponsePaginationTransactionDeleteAtB5Z3github.com/MamangRust/monolith-graphql-ecommerce-pbb\x06proto3"

var (
	file_transaction_transaction_query_proto_rawDescOnce sync.Once
	file_transaction_transaction_query_proto_rawDescData []byte
)

func file_transaction_transaction_query_proto_rawDescGZIP() []byte {
	file_transaction_transaction_query_proto_rawDescOnce.Do(func() {
		file_transaction_transaction_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_transaction_query_proto_rawDesc), len(file_transaction_transaction_query_proto_rawDesc)))
	})
	return file_transaction_transaction_query_proto_rawDescData
}

var file_transaction_transaction_query_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transaction_transaction_query_proto_goTypes = []any{
	(*FindAllTransactionRequest)(nil),                // 0: pb.FindAllTransactionRequest
	(*FindAllTransactionByMerchantRequest)(nil),      // 1: pb.FindAllTransactionByMerchantRequest
	(*FindByOrderIdTransactionRequest)(nil),          // 2: pb.FindByOrderIdTransactionRequest
	(*FindByIdTransactionRequest)(nil),               // 3: pb.FindByIdTransactionRequest
	(*ApiResponsePaginationTransaction)(nil),         // 4: pb.ApiResponsePaginationTransaction
	(*ApiResponseTransaction)(nil),                   // 5: pb.ApiResponseTransaction
	(*ApiResponsePaginationTransactionDeleteAt)(nil), // 6: pb.ApiResponsePaginationTransactionDeleteAt
}
var file_transaction_transaction_query_proto_depIdxs = []int32{
	0, // 0: pb.TransactionQueryService.FindAllTransactions:input_type -> pb.FindAllTransactionRequest
	1, // 1: pb.TransactionQueryService.FindByMerchant:input_type -> pb.FindAllTransactionByMerchantRequest
	3, // 2: pb.TransactionQueryService.FindById:input_type -> pb.FindByIdTransactionRequest
	2, // 3: pb.TransactionQueryService.FindByOrderId:input_type -> pb.FindByOrderIdTransactionRequest
	0, // 4: pb.TransactionQueryService.FindByActive:input_type -> pb.FindAllTransactionRequest
	0, // 5: pb.TransactionQueryService.FindByTrashed:input_type -> pb.FindAllTransactionRequest
	4, // 6: pb.TransactionQueryService.FindAllTransactions:output_type -> pb.ApiResponsePaginationTransaction
	4, // 7: pb.TransactionQueryService.FindByMerchant:output_type -> pb.ApiResponsePaginationTransaction
	5, // 8: pb.TransactionQueryService.FindById:output_type -> pb.ApiResponseTransaction
	5, // 9: pb.TransactionQueryService.FindByOrderId:output_type -> pb.ApiResponseTransaction
	6, // 10: pb.TransactionQueryService.FindByActive:output_type -> pb.ApiResponsePaginationTransactionDeleteAt
	6, // 11: pb.TransactionQueryService.FindByTrashed:output_type -> pb.ApiResponsePaginationTransactionDeleteAt
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_transaction_query_proto_init() }
func file_transaction_transaction_query_proto_init() {
	if File_transaction_transaction_query_proto != nil {
		return
	}
	file_transaction_transaction_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_transaction_query_proto_rawDesc), len(file_transaction_transaction_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_transaction_query_proto_goTypes,
		DependencyIndexes: file_transaction_transaction_query_proto_depIdxs,
		MessageInfos:      file_transaction_transaction_query_proto_msgTypes,
	}.Build()
	File_transaction_transaction_query_proto = out.File
	file_transaction_transaction_query_proto_goTypes = nil
	file_transaction_transaction_query_proto_depIdxs = nil
}
