// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: user/user_query.proto

package monolith_graphql_ecommerce_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllUserRequest) Reset() {
	*x = FindAllUserRequest{}
	mi := &file_user_user_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllUserRequest) ProtoMessage() {}

func (x *FindAllUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllUserRequest.ProtoReflect.Descriptor instead.
func (*FindAllUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllUserRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllUserRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

var File_user_user_query_proto protoreflect.FileDescriptor

const file_user_user_query_proto_rawDesc = "" +
	"\n" +
	"\x15user/user_query.proto\x12\x02pb\x1a\x16user/user_common.proto\"]\n" +
	"\x12FindAllUserRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search2\xc7\x03\n" +
	"\x10UserQueryService\x12@\n" +
	"\aFindAll\x12\x16.pb.FindAllUserRequest\x1a\x1d.pb.ApiResponsePaginationUser\x128\n" +
	"\bFindById\x12\x17.pb.FindByIdUserRequest\x1a\x13.pb.ApiResponseUser\x12F\n" +
	"\vFindByEmail\x12\x16.pb.FindByEmailRequest\x1a\x1f.pb.ApiResponseUserWithPassword\x12P\n" +
	"\x16FindByVerificationCode\x12!.pb.FindByVerificationCodeRequest\x1a\x13.pb.ApiResponseUser\x12M\n" +
	"\fFindByActive\x12\x16.pb.FindAllUserRequest\x1a%.pb.ApiResponsePaginationUserDeleteAt\x12N\n" +
	"\rFindByTrashed\x12\x16.pb.FindAllUserRequest\x1a%.pb.ApiResponsePaginationUserDeleteAtB5Z3github.com/MamangRust/monolith-graphql-ecommerce-pbb\x06proto3"

var (
	file_user_user_query_proto_rawDescOnce sync.Once
	file_user_user_query_proto_rawDescData []byte
)

func file_user_user_query_proto_rawDescGZIP() []byte {
	file_user_user_query_proto_rawDescOnce.Do(func() {
		file_user_user_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_query_proto_rawDesc), len(file_user_user_query_proto_rawDesc)))
	})
	return file_user_user_query_proto_rawDescData
}

var file_user_user_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_user_query_proto_goTypes = []any{
	(*FindAllUserRequest)(nil),                // 0: pb.FindAllUserRequest
	(*FindByIdUserRequest)(nil),               // 1: pb.FindByIdUserRequest
	(*FindByEmailRequest)(nil),                // 2: pb.FindByEmailRequest
	(*FindByVerificationCodeRequest)(nil),     // 3: pb.FindByVerificationCodeRequest
	(*ApiResponsePaginationUser)(nil),         // 4: pb.ApiResponsePaginationUser
	(*ApiResponseUser)(nil),                   // 5: pb.ApiResponseUser
	(*ApiResponseUserWithPassword)(nil),       // 6: pb.ApiResponseUserWithPassword
	(*ApiResponsePaginationUserDeleteAt)(nil), // 7: pb.ApiResponsePaginationUserDeleteAt
}
var file_user_user_query_proto_depIdxs = []int32{
	0, // 0: pb.UserQueryService.FindAll:input_type -> pb.FindAllUserRequest
	1, // 1: pb.UserQueryService.FindById:input_type -> pb.FindByIdUserRequest
	2, // 2: pb.UserQueryService.FindByEmail:input_type -> pb.FindByEmailRequest
	3, // 3: pb.UserQueryService.FindByVerificationCode:input_type -> pb.FindByVerificationCodeRequest
	0, // 4: pb.UserQueryService.FindByActive:input_type -> pb.FindAllUserRequest
	0, // 5: pb.UserQueryService.FindByTrashed:input_type -> pb.FindAllUserRequest
	4, // 6: pb.UserQueryService.FindAll:output_type -> pb.ApiResponsePaginationUser
	5, // 7: pb.UserQueryService.FindById:output_type -> pb.ApiResponseUser
	6, // 8: pb.UserQueryService.FindByEmail:output_type -> pb.ApiResponseUserWithPassword
	5, // 9: pb.UserQueryService.FindByVerificationCode:output_type -> pb.ApiResponseUser
	7, // 10: pb.UserQueryService.FindByActive:output_type -> pb.ApiResponsePaginationUserDeleteAt
	7, // 11: pb.UserQueryService.FindByTrashed:output_type -> pb.ApiResponsePaginationUserDeleteAt
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_query_proto_init() }
func file_user_user_query_proto_init() {
	if File_user_user_query_proto != nil {
		return
	}
	file_user_user_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_query_proto_rawDesc), len(file_user_user_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_query_proto_goTypes,
		DependencyIndexes: file_user_user_query_proto_depIdxs,
		MessageInfos:      file_user_user_query_proto_msgTypes,
	}.Build()
	File_user_user_query_proto = out.File
	file_user_user_query_proto_goTypes = nil
	file_user_user_query_proto_depIdxs = nil
}
