apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- merchant_business-deployment.yaml
- merchant_business-hpa.yaml
- merchant_business-service.yaml
- pdb.yaml
- network-policy.yaml
