package reviewdetailapimapper

import (
	"github.com/MamangRust/monolith-graphql-ecommerce-shared/domain/response"

	pbreview_detail "github.com/MamangRust/monolith-graphql-ecommerce-pb/review_detail"
)

type ReviewDetailBaseResponseMapper interface {
	ToResponseReviewDetail(reviewDetail *pbreview_detail.ReviewDetailsResponse) *response.ReviewDetailsResponse
	ToResponsesReviewDetail(ReviewDetails []*pbreview_detail.ReviewDetailsResponse) []*response.ReviewDetailsResponse
}

type ReviewDetailQueryResponseMapper interface {
	ReviewDetailBaseResponseMapper
	ToApiResponseReviewDetail(pbResponse *pbreview_detail.ApiResponseReviewDetail) *response.ApiResponseReviewDetail
	ToApiResponsesReviewDetail(pbResponse *pbreview_detail.ApiResponsesReviewDetails) *response.ApiResponsesReviewDetails
	ToApiResponsePaginationReviewDetail(pbResponse *pbreview_detail.ApiResponsePaginationReviewDetails) *response.ApiResponsePaginationReviewDetails
	ToApiResponsePaginationReviewDetailDeleteAt(pbResponse *pbreview_detail.ApiResponsePaginationReviewDetailsDeleteAt) *response.ApiResponsePaginationReviewDetailsDeleteAt
}

type ReviewDetailCommandResponseMapper interface {
	ReviewDetailBaseResponseMapper
	ToResponseReviewDetailDeleteAt(reviewDetail *pbreview_detail.ReviewDetailsResponseDeleteAt) *response.ReviewDetailsResponseDeleteAt
	ToResponsesReviewDetailDeleteAt(ReviewDetails []*pbreview_detail.ReviewDetailsResponseDeleteAt) []*response.ReviewDetailsResponseDeleteAt
	ToApiResponseReviewDetailDeleteAt(pbResponse *pbreview_detail.ApiResponseReviewDetailDeleteAt) *response.ApiResponseReviewDetailDeleteAt
	ToApiResponsePaginationReviewDetailDeleteAt(pbResponse *pbreview_detail.ApiResponsePaginationReviewDetailsDeleteAt) *response.ApiResponsePaginationReviewDetailsDeleteAt
}
