package categoryapimapper

import (
	"github.com/MamangRust/monolith-graphql-ecommerce-shared/domain/response"

	pbcategory "github.com/MamangRust/monolith-graphql-ecommerce-pb/category"
)

type CategoryBaseResponseMapper interface {
	ToResponseCategory(category *pbcategory.CategoryResponse) *response.CategoryResponse
	ToResponsesCategory(categories []*pbcategory.CategoryResponse) []*response.CategoryResponse
}

type CategoryQueryResponseMapper interface {
	CategoryBaseResponseMapper
	CategoryStatsResponseMapper
	ToApiResponseCategory(pbResponse *pbcategory.ApiResponseCategory) *response.ApiResponseCategory
	ToApiResponsesCategory(pbResponse *pbcategory.ApiResponsesCategory) *response.ApiResponsesCategory
	ToApiResponsePaginationCategory(pbResponse *pbcategory.ApiResponsePaginationCategory) *response.ApiResponsePaginationCategory
	ToApiResponsePaginationCategoryDeleteAt(pbResponse *pbcategory.ApiResponsePaginationCategoryDeleteAt) *response.ApiResponsePaginationCategoryDeleteAt
}

type CategoryCommandResponseMapper interface {
	CategoryBaseResponseMapper
	ToResponseCategoryDelete(category *pbcategory.CategoryResponseDeleteAt) *response.CategoryResponseDeleteAt
	ToResponsesCategoryDeleteAt(categories []*pbcategory.CategoryResponseDeleteAt) []*response.CategoryResponseDeleteAt
	ToApiResponseCategoryDeleteAt(pbResponse *pbcategory.ApiResponseCategoryDeleteAt) *response.ApiResponseCategoryDeleteAt
	ToApiResponseCategory(pbResponse *pbcategory.ApiResponseCategory) *response.ApiResponseCategory
	ToApiResponseCategoryDelete(pbResponse *pbcategory.ApiResponseCategoryDelete) *response.ApiResponseCategoryDelete
	ToApiResponseCategoryAll(pbResponse *pbcategory.ApiResponseCategoryAll) *response.ApiResponseCategoryAll
	ToApiResponsePaginationCategoryDeleteAt(pbResponse *pbcategory.ApiResponsePaginationCategoryDeleteAt) *response.ApiResponsePaginationCategoryDeleteAt
}

type CategoryStatsResponseMapper interface {
	ToResponseCategoryMonthlyPrice(category *pbcategory.CategoryMonthPriceResponse) *response.CategoryMonthPriceResponse
	ToResponseCategoryMonthlyPrices(c []*pbcategory.CategoryMonthPriceResponse) []*response.CategoryMonthPriceResponse
	ToResponseCategoryYearlyPrice(category *pbcategory.CategoryYearPriceResponse) *response.CategoryYearPriceResponse
	ToResponseCategoryYearlyPrices(c []*pbcategory.CategoryYearPriceResponse) []*response.CategoryYearPriceResponse
	ToResponseCashierMonthlyTotalPrice(c *pbcategory.CategoriesMonthlyTotalPriceResponse) *response.CategoriesMonthlyTotalPriceResponse
	ToResponseCategoryMonthlyTotalPrices(c []*pbcategory.CategoriesMonthlyTotalPriceResponse) []*response.CategoriesMonthlyTotalPriceResponse
	ToResponseCategoryYearlyTotalSale(c *pbcategory.CategoriesYearlyTotalPriceResponse) *response.CategoriesYearlyTotalPriceResponse
	ToResponseCategoryYearlyTotalPrices(c []*pbcategory.CategoriesYearlyTotalPriceResponse) []*response.CategoriesYearlyTotalPriceResponse

	ToApiResponseCategoryMonthPrice(pbResponse *pbcategory.ApiResponseCategoryMonthPrice) *response.ApiResponseCategoryMonthPrice
	ToApiResponseCategoryYearPrice(pbResponse *pbcategory.ApiResponseCategoryYearPrice) *response.ApiResponseCategoryYearPrice
	ToApiResponseCategoryMonthlyTotalPrice(pbResponse *pbcategory.ApiResponseCategoryMonthlyTotalPrice) *response.ApiResponseCategoryMonthlyTotalPrice
	ToApiResponseCategoryYearlyTotalPrice(pbResponse *pbcategory.ApiResponseCategoryYearlyTotalPrice) *response.ApiResponseCategoryYearlyTotalPrice
}
